.TH "BlockInfo" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBposition\fP"
.br
.ti -1c
.RI "int \fBnumber\fP"
.br
.ti -1c
.RI "bool \fBfoldable\fP: 1"
.br
.ti -1c
.RI "bool \fBfolded\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 469 of file jsedit\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool BlockInfo::foldable"

.PP
Definition at line 472 of file jsedit\&.cpp\&.
.SS "bool BlockInfo::folded"

.PP
Definition at line 473 of file jsedit\&.cpp\&.
.SS "int BlockInfo::number"

.PP
Definition at line 471 of file jsedit\&.cpp\&.
.SS "int BlockInfo::position"

.PP
Definition at line 470 of file jsedit\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
