.TH "D:/tixt/corona/qdaq/lib/core/bytearrayprototype.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/bytearrayprototype.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'bytearrayprototype\&.h'\fP
.br
\fC#include <QtScript/QScriptEngine>\fP
.br
\fC#include 'QDaqTypes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T > T \fBreadLE\fP (const char *p, int offset)"
.br
.ti -1c
.RI "template<class T > T \fBreadBE\fP (const char *p, int offset)"
.br
.ti -1c
.RI "template<class T > void \fBwriteLE\fP (const T &v, char *p, int offset)"
.br
.ti -1c
.RI "template<class T > void \fBwriteBE\fP (const T &v, char *p, int offset)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class T > T readBE (const char * p, int offset)"

.PP
Definition at line 78 of file bytearrayprototype\&.cpp\&.
.SS "template<class T > T readLE (const char * p, int offset)"

.PP
Definition at line 73 of file bytearrayprototype\&.cpp\&.
.SS "template<class T > void writeBE (const T & v, char * p, int offset)"

.PP
Definition at line 95 of file bytearrayprototype\&.cpp\&.
.SS "template<class T > void writeLE (const T & v, char * p, int offset)"

.PP
Definition at line 90 of file bytearrayprototype\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
