.TH "Core" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core \- Classes that define the core functionality of \fBQDaq\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQDaqChannel\fP"
.br
.RI "A class that represent a stream of numerical data, a signal\&. "
.ti -1c
.RI "class \fBQDaqDataBuffer\fP"
.br
.RI "A class that provides storage of channel or other data\&. "
.ti -1c
.RI "class \fBQDaqJob\fP"
.br
.ti -1c
.RI "class \fBQDaqLoop\fP"
.br
.RI "A class encapsulating a software loop\&. "
.ti -1c
.RI "struct \fBQDaqError\fP"
.br
.ti -1c
.RI "class \fBQDaqObject\fP"
.br
.ti -1c
.RI "class \fBQDaqRoot\fP"
.br
.ti -1c
.RI "class \fBQDaqTimeValue\fP"
.br
.ti -1c
.RI "class \fBQTimerThread\fP"
.br
.RI "A timer thread class\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QList< \fBQDaqObject\fP * > \fBQDaqObjectList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classes that define the core functionality of \fBQDaq\fP objects\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef QList<\fBQDaqObject\fP*> \fBQDaqObjectList\fP"
A QList of \fBQDaqObject\fP pointers\&. 
.PP
Definition at line 30 of file QDaqObject\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
