.TH "D:/tixt/corona/qdaq/plugins/interfaces Directory Reference" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/plugins/interfaces Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinterfaces\&.cpp\fP"
.br
.ti -1c
.RI "file \fBinterfaces\&.h\fP"
.br
.ti -1c
.RI "file \fBinterfaces_global\&.h\fP"
.br
.ti -1c
.RI "file \fBqdaqmodbus\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqdaqmodbus\&.h\fP"
.br
.ti -1c
.RI "file \fBqdaqserial\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqdaqserial\&.h\fP"
.br
.ti -1c
.RI "file \fBqdaqtcpip\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqdaqtcpip\&.h\fP"
.br
.ti -1c
.RI "file \fBtcp_socket\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtcp_socket\&.h\fP"
.br
.in -1c
