.TH "DisplayDelegate" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DisplayDelegate
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqDelegates\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBupdateDisplay\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisplayDelegate\fP (QWidget *w, \fBQDaqChannel\fP *ch)"
.br
.ti -1c
.RI "virtual \fB~DisplayDelegate\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBWidgetVariant\fP \fBwidget_\fP"
.br
.ti -1c
.RI "QPointer< \fBQDaqChannel\fP > \fBchannel_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file QDaqDelegates\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DisplayDelegate::DisplayDelegate (QWidget * w, \fBQDaqChannel\fP * ch)"

.PP
Definition at line 180 of file QDaqDelegates\&.cpp\&.
.SS "DisplayDelegate::~DisplayDelegate ()\fC [virtual]\fP"

.PP
Definition at line 188 of file QDaqDelegates\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void DisplayDelegate::updateDisplay ()\fC [slot]\fP"

.PP
Definition at line 191 of file QDaqDelegates\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QPointer<\fBQDaqChannel\fP> DisplayDelegate::channel_\fC [protected]\fP"

.PP
Definition at line 60 of file QDaqDelegates\&.h\&.
.SS "\fBWidgetVariant\fP DisplayDelegate::widget_\fC [protected]\fP"

.PP
Definition at line 59 of file QDaqDelegates\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
