.TH "FilterFactory" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilterFactory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <filterfactory\&.h>\fP
.PP
Inherits QObject, and \fBQDaqPlugin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilterFactory\fP ()"
.br
.ti -1c
.RI "virtual QList< const QMetaObject * > \fBpluginClasses\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file filterfactory\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FilterFactory::FilterFactory ()"

.PP
Definition at line 8 of file filterfactory\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QList< const QMetaObject * > FilterFactory::pluginClasses () const\fC [virtual]\fP"

.PP
Implements \fBQDaqPlugin\fP\&.
.PP
Definition at line 12 of file filterfactory\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
