.TH "D:/tixt/corona/qdaq/plugins/filters/filters_global.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/plugins/filters/filters_global.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/qglobal\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFILTERSSHARED_EXPORT\fP   Q_DECL_IMPORT"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FILTERSSHARED_EXPORT   Q_DECL_IMPORT"

.PP
Definition at line 10 of file filters_global\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
