.TH "FormattedPicker" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormattedPicker
.SH SYNOPSIS
.br
.PP
.PP
Inherits QwtPlotPicker\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormattedPicker\fP (int xAxis, int yAxis, RubberBand rubberBand, DisplayMode trackerMode, QWidget *pc)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual QwtText \fBtrackerTextF\fP (const QPointF &pos) const"
.br
.ti -1c
.RI "QString \fBcreateLabelText\fP (const QPointF &pos) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file QDaqPlotWidget\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FormattedPicker::FormattedPicker (int xAxis, int yAxis, RubberBand rubberBand, DisplayMode trackerMode, QWidget * pc)\fC [inline]\fP"

.PP
Definition at line 26 of file QDaqPlotWidget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString FormattedPicker::createLabelText (const QPointF & pos) const\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 44 of file QDaqPlotWidget\&.cpp\&.
.SS "virtual QwtText FormattedPicker::trackerTextF (const QPointF & pos) const\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 32 of file QDaqPlotWidget\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
