.TH "h5helper::deferedPtrData" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
h5helper::deferedPtrData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qdaqh5file\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdeferedPtrData\fP (\fBQDaqObject\fP *o=0, const char *n=0, const QString &p=QString())"
.br
.ti -1c
.RI "\fBdeferedPtrData\fP (\fBQDaqObject\fP *o, const char *n, const QStringList &p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQDaqObject\fP * \fBobj\fP"
.br
.ti -1c
.RI "const char * \fBpropName\fP"
.br
.ti -1c
.RI "QStringList \fBpathList\fP"
.br
.ti -1c
.RI "bool \fBisList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 72 of file qdaqh5file\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "h5helper::deferedPtrData::deferedPtrData (\fBQDaqObject\fP * o = \fC0\fP, const char * n = \fC0\fP, const QString & p = \fCQString()\fP)\fC [inline]\fP"

.PP
Definition at line 77 of file qdaqh5file\&.h\&.
.SS "h5helper::deferedPtrData::deferedPtrData (\fBQDaqObject\fP * o, const char * n, const QStringList & p)\fC [inline]\fP"

.PP
Definition at line 82 of file qdaqh5file\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool h5helper::deferedPtrData::isList"

.PP
Definition at line 76 of file qdaqh5file\&.h\&.
.SS "\fBQDaqObject\fP* h5helper::deferedPtrData::obj"

.PP
Definition at line 73 of file qdaqh5file\&.h\&.
.SS "QStringList h5helper::deferedPtrData::pathList"

.PP
Definition at line 75 of file qdaqh5file\&.h\&.
.SS "const char* h5helper::deferedPtrData::propName"

.PP
Definition at line 74 of file qdaqh5file\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
