.TH "h5helper" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
h5helper
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qdaqh5file\&.h>\fP
.PP
Inherited by \fBh5helper_v1_0\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdeferedPtrData\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBh5helper\fP (\fBQDaqH5File::Version\fP v, int mj, int mn, \fBQDaqH5File\fP *f)"
.br
.ti -1c
.RI "virtual \fB~h5helper\fP ()"
.br
.ti -1c
.RI "\fBQDaqH5File::Version\fP \fBversion\fP () const"
.br
.ti -1c
.RI "int \fBmajor\fP () const"
.br
.ti -1c
.RI "int \fBminor\fP () const"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (CommonFG *h5obj, const char *name, const int &v)=0"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (CommonFG *h5obj, const char *name, const double &v)=0"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (CommonFG *h5obj, const char *name, const QString &S)=0"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (CommonFG *h5obj, const char *name, const QStringList &S)=0"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (CommonFG *h5obj, const char *name, const \fBQDaqVector\fP &value)=0"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (CommonFG *h5obj, const char *name, const \fBQDaqObject\fP *obj)=0"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (CommonFG *, const char *, const \fBQDaqObjectList\fP &)=0"
.br
.ti -1c
.RI "virtual bool \fBread\fP (CommonFG *h5obj, const char *name, int &value)=0"
.br
.ti -1c
.RI "virtual bool \fBread\fP (CommonFG *h5obj, const char *name, double &value)=0"
.br
.ti -1c
.RI "virtual bool \fBread\fP (CommonFG *h5obj, const char *name, QString &str)=0"
.br
.ti -1c
.RI "virtual bool \fBread\fP (CommonFG *h5obj, const char *name, QStringList &S)=0"
.br
.ti -1c
.RI "virtual bool \fBread\fP (CommonFG *h5obj, const char *name, \fBQDaqVector\fP &value)=0"
.br
.ti -1c
.RI "virtual void \fBwriteProperties\fP (CommonFG *h5obj, const \fBQDaqObject\fP *m_object, const QMetaObject *metaObject)=0"
.br
.ti -1c
.RI "virtual void \fBreadProperties\fP (CommonFG *h5obj, \fBQDaqObject\fP *obj)=0"
.br
.ti -1c
.RI "virtual void \fBlockedPropertyList\fP (QStringList S=QStringList())=0"
.br
.ti -1c
.RI "virtual void \fBconnectDeferedPointers\fP ()=0"
.br
.ti -1c
.RI "virtual Group \fBcreateGroup\fP (CommonFG *loc, const char *name)=0"
.br
.ti -1c
.RI "virtual QByteArrayList \fBgetGroupNames\fP (CommonFG *h5obj, bool isRoot=false)=0"
.br
.ti -1c
.RI "bool \fBh5exist_ds\fP (CommonFG *h5obj, const char *name)"
.br
.ti -1c
.RI "QString \fBgroupName\fP (CommonFG *h5obj)"
.br
.ti -1c
.RI "void \fBpushWarning\fP (const QString &w)"
.br
.ti -1c
.RI "void \fBdeferObjPtrRead\fP (\fBQDaqObject\fP *obj, const char *name, const QString &path)"
.br
.ti -1c
.RI "void \fBdeferObjPtrRead\fP (\fBQDaqObject\fP *obj, const char *name, const QStringList &pathList)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBwriteDynamicProperties\fP (CommonFG *h5obj, const \fBQDaqObject\fP *m_object)=0"
.br
.ti -1c
.RI "virtual void \fBreadDynamicProperties\fP (CommonFG *h5obj, \fBQDaqObject\fP *m_object)=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBQDaqH5File::Version\fP \fBver_\fP"
.br
.ti -1c
.RI "int \fBmajor_\fP"
.br
.ti -1c
.RI "int \fBminor_\fP"
.br
.ti -1c
.RI "\fBQDaqH5File\fP * \fBfile_\fP"
.br
.ti -1c
.RI "QList< \fBdeferedPtrData\fP > \fBdeferedPtrs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file qdaqh5file\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "h5helper::h5helper (\fBQDaqH5File::Version\fP v, int mj, int mn, \fBQDaqH5File\fP * f)\fC [inline]\fP"

.PP
Definition at line 90 of file qdaqh5file\&.h\&.
.SS "virtual h5helper::~h5helper ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 93 of file qdaqh5file\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void h5helper::connectDeferedPointers ()\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP, and \fBh5helper_v1_1\fP\&.
.SS "virtual Group h5helper::createGroup (CommonFG * loc, const char * name)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP, and \fBh5helper_v1_1\fP\&.
.SS "void h5helper::deferObjPtrRead (\fBQDaqObject\fP * obj, const char * name, const QString & path)"

.PP
Definition at line 351 of file qdaqh5file\&.cpp\&.
.SS "void h5helper::deferObjPtrRead (\fBQDaqObject\fP * obj, const char * name, const QStringList & pathList)"

.PP
Definition at line 357 of file qdaqh5file\&.cpp\&.
.SS "virtual QByteArrayList h5helper::getGroupNames (CommonFG * h5obj, bool isRoot = \fCfalse\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_1\fP, and \fBh5helper_v1_0\fP\&.
.SS "QString h5helper::groupName (CommonFG * h5obj)"

.PP
Definition at line 341 of file qdaqh5file\&.cpp\&.
.SS "bool h5helper::h5exist_ds (CommonFG * h5obj, const char * name)"

.PP
Definition at line 333 of file qdaqh5file\&.cpp\&.
.SS "virtual void h5helper::lockedPropertyList (QStringList S = \fCQStringList()\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP, and \fBh5helper_v1_1\fP\&.
.SS "int h5helper::major () const\fC [inline]\fP"

.PP
Definition at line 98 of file qdaqh5file\&.h\&.
.SS "int h5helper::minor () const\fC [inline]\fP"

.PP
Definition at line 99 of file qdaqh5file\&.h\&.
.SS "void h5helper::pushWarning (const QString & w)\fC [inline]\fP"

.PP
Definition at line 131 of file qdaqh5file\&.h\&.
.SS "virtual bool h5helper::read (CommonFG * h5obj, const char * name, double & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP\&.
.SS "virtual bool h5helper::read (CommonFG * h5obj, const char * name, int & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP\&.
.SS "virtual bool h5helper::read (CommonFG * h5obj, const char * name, \fBQDaqVector\fP & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP\&.
.SS "virtual bool h5helper::read (CommonFG * h5obj, const char * name, QString & str)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP\&.
.SS "virtual bool h5helper::read (CommonFG * h5obj, const char * name, QStringList & S)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP\&.
.SS "virtual void h5helper::readDynamicProperties (CommonFG * h5obj, \fBQDaqObject\fP * m_object)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP, and \fBh5helper_v1_1\fP\&.
.SS "virtual void h5helper::readProperties (CommonFG * h5obj, \fBQDaqObject\fP * obj)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP\&.
.SS "\fBQDaqH5File::Version\fP h5helper::version () const\fC [inline]\fP"

.PP
Definition at line 96 of file qdaqh5file\&.h\&.
.SS "virtual void h5helper::write (CommonFG *, const char *, const \fBQDaqObjectList\fP &)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_1\fP, and \fBh5helper_v1_0\fP\&.
.SS "virtual void h5helper::write (CommonFG * h5obj, const char * name, const double & v)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP\&.
.SS "virtual void h5helper::write (CommonFG * h5obj, const char * name, const int & v)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP\&.
.SS "virtual void h5helper::write (CommonFG * h5obj, const char * name, const \fBQDaqObject\fP * obj)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_1\fP, and \fBh5helper_v1_0\fP\&.
.SS "virtual void h5helper::write (CommonFG * h5obj, const char * name, const \fBQDaqVector\fP & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP\&.
.SS "virtual void h5helper::write (CommonFG * h5obj, const char * name, const QString & S)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP\&.
.SS "virtual void h5helper::write (CommonFG * h5obj, const char * name, const QStringList & S)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP\&.
.SS "virtual void h5helper::writeDynamicProperties (CommonFG * h5obj, const \fBQDaqObject\fP * m_object)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP, and \fBh5helper_v1_1\fP\&.
.SS "virtual void h5helper::writeProperties (CommonFG * h5obj, const \fBQDaqObject\fP * m_object, const QMetaObject * metaObject)\fC [pure virtual]\fP"

.PP
Implemented in \fBh5helper_v1_0\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QList<\fBdeferedPtrData\fP> h5helper::deferedPtrs\fC [protected]\fP"

.PP
Definition at line 87 of file qdaqh5file\&.h\&.
.SS "\fBQDaqH5File\fP* h5helper::file_\fC [protected]\fP"

.PP
Definition at line 67 of file qdaqh5file\&.h\&.
.SS "int h5helper::major_\fC [protected]\fP"

.PP
Definition at line 66 of file qdaqh5file\&.h\&.
.SS "int h5helper::minor_\fC [protected]\fP"

.PP
Definition at line 66 of file qdaqh5file\&.h\&.
.SS "\fBQDaqH5File::Version\fP h5helper::ver_\fC [protected]\fP"

.PP
Definition at line 65 of file qdaqh5file\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
