.TH "D:/tixt/corona/qdaq/lib/core/h5helper_v1_0.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/h5helper_v1_0.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'h5helper_v1_0\&.h'\fP
.br
\fC#include 'QDaqVector\&.h'\fP
.br
\fC#include 'QDaqObject\&.h'\fP
.br
\fC#include <QMetaProperty>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLASS_ATTR_NAME\fP   'Class'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CLASS_ATTR_NAME   'Class'"

.PP
Definition at line 9 of file h5helper_v1_0\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
