.TH "D:/tixt/corona/qdaq/plugins/interfaces/interfaces.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/plugins/interfaces/interfaces.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'interfaces\&.h'\fP
.br
\fC#include 'qdaqserial\&.h'\fP
.br
\fC#include 'qdaqtcpip\&.h'\fP
.br
\fC#include 'qdaqmodbus\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
