.TH "Interfaces" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interfaces
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interfaces\&.h>\fP
.PP
Inherits QObject, and \fBQDaqPlugin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterfaces\fP ()"
.br
.ti -1c
.RI "virtual QList< const QMetaObject * > \fBpluginClasses\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file interfaces\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Interfaces::Interfaces ()"

.PP
Definition at line 6 of file interfaces\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QList< const QMetaObject * > Interfaces::pluginClasses () const\fC [virtual]\fP"

.PP
Implements \fBQDaqPlugin\fP\&.
.PP
Definition at line 10 of file interfaces\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
