.TH "JSBlockData" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JSBlockData
.SH SYNOPSIS
.br
.PP
.PP
Inherits QTextBlockUserData\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QList< int > \fBbracketPositions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file jsedit\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QList<int> JSBlockData::bracketPositions"

.PP
Definition at line 38 of file jsedit\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
