.TH "JSEditPrivate" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JSEditPrivate
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBJSEdit\fP * \fBeditor\fP"
.br
.ti -1c
.RI "\fBJSDocLayout\fP * \fBlayout\fP"
.br
.ti -1c
.RI "\fBJSHighlighter\fP * \fBhighlighter\fP"
.br
.ti -1c
.RI "\fBSidebarWidget\fP * \fBsidebar\fP"
.br
.ti -1c
.RI "bool \fBshowLineNumbers\fP"
.br
.ti -1c
.RI "bool \fBtextWrap\fP"
.br
.ti -1c
.RI "QColor \fBcursorColor\fP"
.br
.ti -1c
.RI "bool \fBbracketsMatching\fP"
.br
.ti -1c
.RI "QList< int > \fBmatchPositions\fP"
.br
.ti -1c
.RI "QColor \fBbracketMatchColor\fP"
.br
.ti -1c
.RI "QList< int > \fBerrorPositions\fP"
.br
.ti -1c
.RI "QColor \fBbracketErrorColor\fP"
.br
.ti -1c
.RI "bool \fBcodeFolding\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 656 of file jsedit\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QColor JSEditPrivate::bracketErrorColor"

.PP
Definition at line 670 of file jsedit\&.cpp\&.
.SS "QColor JSEditPrivate::bracketMatchColor"

.PP
Definition at line 668 of file jsedit\&.cpp\&.
.SS "bool JSEditPrivate::bracketsMatching"

.PP
Definition at line 666 of file jsedit\&.cpp\&.
.SS "bool JSEditPrivate::codeFolding"

.PP
Definition at line 671 of file jsedit\&.cpp\&.
.SS "QColor JSEditPrivate::cursorColor"

.PP
Definition at line 665 of file jsedit\&.cpp\&.
.SS "\fBJSEdit\fP* JSEditPrivate::editor"

.PP
Definition at line 659 of file jsedit\&.cpp\&.
.SS "QList<int> JSEditPrivate::errorPositions"

.PP
Definition at line 669 of file jsedit\&.cpp\&.
.SS "\fBJSHighlighter\fP* JSEditPrivate::highlighter"

.PP
Definition at line 661 of file jsedit\&.cpp\&.
.SS "\fBJSDocLayout\fP* JSEditPrivate::layout"

.PP
Definition at line 660 of file jsedit\&.cpp\&.
.SS "QList<int> JSEditPrivate::matchPositions"

.PP
Definition at line 667 of file jsedit\&.cpp\&.
.SS "bool JSEditPrivate::showLineNumbers"

.PP
Definition at line 663 of file jsedit\&.cpp\&.
.SS "\fBSidebarWidget\fP* JSEditPrivate::sidebar"

.PP
Definition at line 662 of file jsedit\&.cpp\&.
.SS "bool JSEditPrivate::textWrap"

.PP
Definition at line 664 of file jsedit\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
