.TH "D:/tixt/corona/qdaq/lib/3rdparty/jsedit/jsedit.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/3rdparty/jsedit/jsedit.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'jsedit\&.h'\fP
.br
\fC#include <QtGui>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJSBlockData\fP"
.br
.ti -1c
.RI "class \fBJSHighlighter\fP"
.br
.ti -1c
.RI "struct \fBBlockInfo\fP"
.br
.ti -1c
.RI "class \fBSidebarWidget\fP"
.br
.ti -1c
.RI "class \fBJSDocLayout\fP"
.br
.ti -1c
.RI "class \fBJSEditPrivate\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBQ_DECLARE_TYPEINFO\fP (\fBBlockInfo\fP, Q_PRIMITIVE_TYPE)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Q_DECLARE_TYPEINFO (\fBBlockInfo\fP, Q_PRIMITIVE_TYPE)"

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
