.TH "D:/tixt/corona/qdaq/lib/3rdparty/kled/kled.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/3rdparty/kled/kled.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'kled\&.h'\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QImage>\fP
.br
\fC#include <QStyle>\fP
.br
\fC#include <QStyleOption>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKLed\fP"
.br
.RI "An LED widget\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
