.TH "KLed" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KLed \- An LED widget\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <KLed>\fP
.PP
Inherits Private\&.
.PP
Inherited by \fBQDaqLed\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBState\fP { \fBOff\fP, \fBOn\fP }"
.br
.RI "LED on/off\&. "
.ti -1c
.RI "enum \fBShape\fP { \fBRectangular\fP, \fBCircular\fP }"
.br
.RI "LED shape\&. "
.ti -1c
.RI "enum \fBLook\fP { \fBFlat\fP, \fBRaised\fP, \fBSunken\fP }"
.br
.RI "LED look\&. "
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBtoggle\fP ()"
.br
.ti -1c
.RI "void \fBon\fP ()"
.br
.ti -1c
.RI "void \fBoff\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrivate\fP ()"
.br
.ti -1c
.RI "\fBKLed\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fBKLed\fP (const QColor &\fBcolor\fP, QWidget *parent=nullptr)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBKLed\fP (const QColor &\fBcolor\fP, \fBKLed::State\fP \fBstate\fP, \fBKLed::Look\fP \fBlook\fP, \fBKLed::Shape\fP \fBshape\fP, QWidget *parent=nullptr)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~KLed\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "QColor \fBcolor\fP () const"
.br
.ti -1c
.RI "\fBState\fP \fBstate\fP () const"
.br
.ti -1c
.RI "\fBLook\fP \fBlook\fP () const"
.br
.ti -1c
.RI "\fBShape\fP \fBshape\fP () const"
.br
.ti -1c
.RI "int \fBdarkFactor\fP () const"
.br
.ti -1c
.RI "void \fBsetColor\fP (const QColor &\fBcolor\fP)"
.br
.ti -1c
.RI "void \fBsetState\fP (\fBState\fP \fBstate\fP)"
.br
.ti -1c
.RI "void \fBsetLook\fP (\fBLook\fP \fBlook\fP)"
.br
.ti -1c
.RI "void \fBsetShape\fP (\fBShape\fP \fBshape\fP)"
.br
.RI "Set LED shape\&. "
.ti -1c
.RI "void \fBsetDarkFactor\fP (int \fBdarkFactor\fP)"
.br
.ti -1c
.RI "QSize \fBsizeHint\fP () const Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "QSize \fBminimumSizeHint\fP () const Q_DECL_OVERRIDE"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdarkFactor\fP"
.br
.ti -1c
.RI "QColor \fBcolor\fP"
.br
.ti -1c
.RI "\fBState\fP \fBstate\fP"
.br
.ti -1c
.RI "\fBLook\fP \fBlook\fP"
.br
.ti -1c
.RI "\fBShape\fP \fBshape\fP"
.br
.ti -1c
.RI "QPixmap \fBcachedPixmap\fP [2]"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *) Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "void \fBresizeEvent\fP (QResizeEvent *) Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "void \fBupdateCachedPixmap\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
An LED widget\&. 

Displays a round or rectangular light emitting diode\&.
.PP
It is configurable to arbitrary colors, the two on/off states and three styles (or 'looks');
.PP
It may display itself in a performant flat view, a round view with light spot or a round view sunken in the screen\&.
.PP
KLed Widget
.PP
\fBAuthor\fP
.RS 4
Joerg Habenicht, Richard J\&. Moore (rich@kde.org) 1998, 1999 
.RE
.PP

.PP
Definition at line 29 of file kled\&.cpp\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBKLed::Look\fP"

.PP
LED look\&. Displays a flat, round or sunken LED\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFlat \fP\fP
.TP
\fB\fIRaised \fP\fP
.TP
\fB\fISunken \fP\fP
.PP
Definition at line 79 of file kled\&.h\&.
.SS "enum \fBKLed::Shape\fP"

.PP
LED shape\&. Shades of the lamp\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRectangular \fP\fP
.TP
\fB\fICircular \fP\fP
.PP
Definition at line 71 of file kled\&.h\&.
.SS "enum \fBKLed::State\fP"

.PP
LED on/off\&. Status of the light is on/off\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOff \fP\fP
.TP
\fB\fIOn \fP\fP
.PP
Definition at line 64 of file kled\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KLed::KLed (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"
Constructs a green, round LED widget which will initially be turned on\&.
.PP
\fBParameters\fP
.RS 4
\fIparent\fP The parent widget\&. 
.RE
.PP

.PP
Definition at line 47 of file kled\&.cpp\&.
.SS "KLed::KLed (const QColor & color, QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Constructor\&. Constructs a round LED widget with the supplied color which will initially be turned on\&.
.PP
\fBParameters\fP
.RS 4
\fIcolor\fP Initial color of the LED\&. 
.br
\fIparent\fP The parent widget\&. 
.RE
.PP

.PP
Definition at line 55 of file kled\&.cpp\&.
.SS "KLed::KLed (const QColor & color, \fBKLed::State\fP state, \fBKLed::Look\fP look, \fBKLed::Shape\fP shape, QWidget * parent = \fCnullptr\fP)"

.PP
Constructor\&. Constructor with the color, state and look\&.
.PP
Differs from above only in the parameters, which configure all settings\&.
.PP
\fBParameters\fP
.RS 4
\fIcolor\fP Initial color of the LED\&. 
.br
\fIstate\fP Sets the State\&. 
.br
\fIlook\fP Sets the Look\&. 
.br
\fIshape\fP Sets the Shape (rectangular or circular)\&. 
.br
\fIparent\fP The parent widget\&. 
.RE
.PP

.PP
Definition at line 63 of file kled\&.cpp\&.
.SS "KLed::~KLed ()"

.PP
Destructor\&. Destroys the LED widget\&. 
.PP
Definition at line 76 of file kled\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QColor KLed::color () const"
Returns the current color of the widget\&.
.PP
\fBReturns\fP
.RS 4
LED color 
.RE
.PP
\fBSee also\fP
.RS 4
\fBsetColor()\fP 
.RE
.PP

.SS "int KLed::darkFactor () const"
Returns the factor to darken the LED\&. 
.PP
\fBReturns\fP
.RS 4
dark factor
.RE
.PP
\fBSee also\fP
.RS 4
\fBsetDarkFactor()\fP 
.RE
.PP

.SS "\fBLook\fP KLed::look () const"
Returns the current look of the widget\&. 
.PP
\fBReturns\fP
.RS 4
LED look
.RE
.PP
\fBSee also\fP
.RS 4
\fBLook\fP 
.RE
.PP

.SS "QSize KLed::minimumSizeHint () const"

.PP
Definition at line 187 of file kled\&.cpp\&.
.SS "void KLed::off ()\fC [slot]\fP"
Sets the state of the widget to Off\&.
.PP
\fBSee also\fP
.RS 4
\fBon()\fP \fBtoggle()\fP \fBsetState()\fP 
.RE
.PP

.PP
Definition at line 169 of file kled\&.cpp\&.
.SS "void KLed::on ()\fC [slot]\fP"
Sets the state of the widget to On\&.
.PP
\fBSee also\fP
.RS 4
\fBoff()\fP \fBtoggle()\fP \fBsetState()\fP 
.RE
.PP

.PP
Definition at line 164 of file kled\&.cpp\&.
.SS "void KLed::paintEvent (QPaintEvent *)\fC [protected]\fP"

.PP
Definition at line 214 of file kled\&.cpp\&.
.SS "KLed::Private ()\fC [inline]\fP"

.PP
Definition at line 32 of file kled\&.cpp\&.
.SS "void KLed::resizeEvent (QResizeEvent *)\fC [protected]\fP"

.PP
Definition at line 174 of file kled\&.cpp\&.
.SS "void KLed::setColor (const QColor & color)"
Set the color of the widget\&.
.PP
The LED is shown with \fCcolor\fP when in the \fBKLed::On\fP state or with the darken color in \fBKLed::Off\fP state\&.
.PP
The widget calls the update() method, so it will be updated when entering the main event loop\&.
.PP
\fBParameters\fP
.RS 4
\fIcolor\fP New color of the LED\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBcolor()\fP \fBdarkFactor()\fP 
.RE
.PP

.PP
Definition at line 122 of file kled\&.cpp\&.
.SS "void KLed::setDarkFactor (int darkFactor)"
Sets the factor to darken the LED in \fBKLed::Off\fP state\&.
.PP
The \fCdarkFactor\fP should be greater than 100, otherwise the LED becomes lighter in \fBKLed::Off\fP state\&.
.PP
Defaults to 300\&.
.PP
\fBParameters\fP
.RS 4
\fIdarkFactor\fP Sets the factor to darken the LED\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBsetColor\fP 
.RE
.PP

.PP
Definition at line 132 of file kled\&.cpp\&.
.SS "void KLed::setLook (\fBLook\fP look)"
Sets the look of the widget\&.
.PP
The look may be Flat, Raised or Sunken\&.
.PP
The widget calls the update() method, so it will be updated when entering the main event loop\&.
.PP
\fBParameters\fP
.RS 4
\fIlook\fP New look of the LED\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBLook\fP 
.RE
.PP

.PP
Definition at line 147 of file kled\&.cpp\&.
.SS "void KLed::setShape (\fBShape\fP shape)"

.PP
Set LED shape\&. Set the shape of the LED\&.
.PP
\fBParameters\fP
.RS 4
\fIshape\fP The LED shape\&. 
.RE
.PP

.PP
Definition at line 112 of file kled\&.cpp\&.
.SS "void KLed::setState (\fBState\fP state)"
Sets the state of the widget to On or Off\&.
.PP
\fBParameters\fP
.RS 4
\fIstate\fP The LED state: on or off\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBon()\fP \fBoff()\fP \fBtoggle()\fP 
.RE
.PP

.PP
Definition at line 101 of file kled\&.cpp\&.
.SS "\fBShape\fP KLed::shape () const"
Returns the current shape of the widget\&. 
.PP
\fBReturns\fP
.RS 4
LED shape
.RE
.PP
\fBSee also\fP
.RS 4
\fBShape\fP 
.RE
.PP

.SS "QSize KLed::sizeHint () const"

.PP
Definition at line 179 of file kled\&.cpp\&.
.SS "\fBState\fP KLed::state () const"
Returns the current state of the widget (on/off)\&. 
.PP
\fBReturns\fP
.RS 4
LED state
.RE
.PP
\fBSee also\fP
.RS 4
\fBState\fP 
.RE
.PP

.SS "void KLed::toggle ()\fC [slot]\fP"
Toggles the state of the led from Off to On or vice versa\&. 
.PP
Definition at line 157 of file kled\&.cpp\&.
.SS "void KLed::updateCachedPixmap ()\fC [protected]\fP"

.PP
Definition at line 207 of file kled\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QPixmap KLed::cachedPixmap[2]"

.PP
Definition at line 44 of file kled\&.cpp\&.
.SS "QColor KLed::color\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 39 of file kled\&.cpp\&.
.SS "int KLed::darkFactor\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 38 of file kled\&.cpp\&.
.SS "\fBLook\fP KLed::look\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 41 of file kled\&.cpp\&.
.SS "\fBShape\fP KLed::shape\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 42 of file kled\&.cpp\&.
.SS "\fBState\fP KLed::state\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 40 of file kled\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
