.TH "D:/tixt/corona/qdaq/plugins/linux-gpib/linuxgpib.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/plugins/linux-gpib/linuxgpib.h
.SH SYNOPSIS
.br
.PP
\fC#include 'linux\-gpib_global\&.h'\fP
.br
\fC#include 'qdaqplugin\&.h'\fP
.br
\fC#include 'QDaqInterface\&.h'\fP
.br
\fC#include 'QDaqVector\&.h'\fP
.br
\fC#include <QtPlugin>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPluginFactory\fP"
.br
.ti -1c
.RI "class \fBQDaqLinuxGpib\fP"
.br
.RI "A class for accesing a GPIB interface\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
