.TH "math::running_average< T, N >" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math::running_average< T, N >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <math_util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrunning_average\fP (const T &v=0)"
.br
.ti -1c
.RI "\fBrunning_average\fP & \fBoperator<<\fP (const T &v)"
.br
.ti -1c
.RI "T \fBoperator()\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T, int N>
.br
class math::running_average< T, N >"

.PP
Definition at line 123 of file math_util\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T , int N> \fBmath::running_average\fP< T, N >::\fBrunning_average\fP (const T & v = \fC0\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 128 of file math_util\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T , int N> void \fBmath::running_average\fP< T, N >::clear ()\fC [inline]\fP"

.PP
Definition at line 147 of file math_util\&.h\&.
.SS "template<class T , int N> T \fBmath::running_average\fP< T, N >::operator() ()\fC [inline]\fP"

.PP
Definition at line 141 of file math_util\&.h\&.
.SS "template<class T , int N> \fBrunning_average\fP& \fBmath::running_average\fP< T, N >::operator<< (const T & v)\fC [inline]\fP"

.PP
Definition at line 135 of file math_util\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
