.TH "math::buffer< T >" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math::buffer< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <math_util\&.h>\fP
.PP
Inherits QSharedData\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef QVector< T > \fBcontainer_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbuffer\fP (int acap=0)"
.br
.ti -1c
.RI "\fBbuffer\fP (const \fB_Self\fP &rhs)"
.br
.ti -1c
.RI "\fB~buffer\fP (void)"
.br
.ti -1c
.RI "\fB_Self\fP & \fBoperator=\fP (const \fB_Self\fP &rhs)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fB_Self\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fB_Self\fP &rhs) const"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "bool \fBisCircular\fP () const"
.br
.ti -1c
.RI "void \fBsetCircular\fP (bool on)"
.br
.ti -1c
.RI "int \fBcapacity\fP () const"
.br
.ti -1c
.RI "void \fBsetCapacity\fP (int c)"
.br
.ti -1c
.RI "void \fBsetSize\fP (int n)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "T & \fBoperator[]\fP (int i)"
.br
.ti -1c
.RI "const T & \fBoperator[]\fP (int i) const"
.br
.ti -1c
.RI "const T & \fBget\fP (int i) const"
.br
.ti -1c
.RI "void \fBpush\fP (const T &v)"
.br
.ti -1c
.RI "void \fBpush\fP (const T *v, int n)"
.br
.ti -1c
.RI "void \fBpop\fP ()"
.br
.ti -1c
.RI "const T * \fBconstData\fP () const"
.br
.ti -1c
.RI "T * \fBdata\fP ()"
.br
.ti -1c
.RI "\fBcontainer_t\fP \fBvector\fP () const"
.br
.ti -1c
.RI "double \fBvmin\fP () const"
.br
.ti -1c
.RI "double \fBvmax\fP () const"
.br
.ti -1c
.RI "double \fBmean\fP () const"
.br
.ti -1c
.RI "double \fBstd\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class math::buffer< T >"

.PP
Definition at line 156 of file math_util\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class T > typedef QVector<T> \fBmath::buffer\fP< T >::\fBcontainer_t\fP"

.PP
Definition at line 159 of file math_util\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBmath::buffer\fP< T >::\fBbuffer\fP (int acap = \fC0\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 255 of file math_util\&.h\&.
.SS "template<class T > \fBmath::buffer\fP< T >::\fBbuffer\fP (const \fB_Self\fP & rhs)\fC [inline]\fP"

.PP
Definition at line 260 of file math_util\&.h\&.
.SS "template<class T > \fBmath::buffer\fP< T >::~\fBbuffer\fP (void)\fC [inline]\fP"

.PP
Definition at line 265 of file math_util\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T > int \fBmath::buffer\fP< T >::capacity () const\fC [inline]\fP"

.PP
Definition at line 309 of file math_util\&.h\&.
.SS "template<class T > void \fBmath::buffer\fP< T >::clear ()\fC [inline]\fP"

.PP
Definition at line 348 of file math_util\&.h\&.
.SS "template<class T > const T* \fBmath::buffer\fP< T >::constData () const\fC [inline]\fP"

.PP
Definition at line 417 of file math_util\&.h\&.
.SS "template<class T > T* \fBmath::buffer\fP< T >::data ()\fC [inline]\fP"

.PP
Definition at line 422 of file math_util\&.h\&.
.SS "template<class T > const T& \fBmath::buffer\fP< T >::get (int i) const\fC [inline]\fP"

.PP
Definition at line 364 of file math_util\&.h\&.
.SS "template<class T > bool \fBmath::buffer\fP< T >::isCircular () const\fC [inline]\fP"

.PP
Definition at line 300 of file math_util\&.h\&.
.SS "template<class T > double \fBmath::buffer\fP< T >::mean () const\fC [inline]\fP"

.PP
Definition at line 444 of file math_util\&.h\&.
.SS "template<class T > bool \fBmath::buffer\fP< T >::operator!= (const \fB_Self\fP & rhs) const\fC [inline]\fP"

.PP
Definition at line 293 of file math_util\&.h\&.
.SS "template<class T > \fB_Self\fP& \fBmath::buffer\fP< T >::operator= (const \fB_Self\fP & rhs)\fC [inline]\fP"

.PP
Definition at line 269 of file math_util\&.h\&.
.SS "template<class T > bool \fBmath::buffer\fP< T >::operator== (const \fB_Self\fP & rhs) const\fC [inline]\fP"

.PP
Definition at line 282 of file math_util\&.h\&.
.SS "template<class T > T& \fBmath::buffer\fP< T >::operator[] (int i)\fC [inline]\fP"

.PP
Definition at line 356 of file math_util\&.h\&.
.SS "template<class T > const T& \fBmath::buffer\fP< T >::operator[] (int i) const\fC [inline]\fP"

.PP
Definition at line 360 of file math_util\&.h\&.
.SS "template<class T > void \fBmath::buffer\fP< T >::pop ()\fC [inline]\fP"

.PP
Definition at line 410 of file math_util\&.h\&.
.SS "template<class T > void \fBmath::buffer\fP< T >::push (const T & v)\fC [inline]\fP"

.PP
Definition at line 368 of file math_util\&.h\&.
.SS "template<class T > void \fBmath::buffer\fP< T >::push (const T * v, int n)\fC [inline]\fP"

.PP
Definition at line 380 of file math_util\&.h\&.
.SS "template<class T > void \fBmath::buffer\fP< T >::setCapacity (int c)\fC [inline]\fP"

.PP
Definition at line 311 of file math_util\&.h\&.
.SS "template<class T > void \fBmath::buffer\fP< T >::setCircular (bool on)\fC [inline]\fP"

.PP
Definition at line 301 of file math_util\&.h\&.
.SS "template<class T > void \fBmath::buffer\fP< T >::setSize (int n)\fC [inline]\fP"

.PP
Definition at line 338 of file math_util\&.h\&.
.SS "template<class T > int \fBmath::buffer\fP< T >::size () const\fC [inline]\fP"

.PP
Definition at line 298 of file math_util\&.h\&.
.SS "template<class T > double \fBmath::buffer\fP< T >::std () const\fC [inline]\fP"

.PP
Definition at line 451 of file math_util\&.h\&.
.SS "template<class T > \fBcontainer_t\fP \fBmath::buffer\fP< T >::vector () const\fC [inline]\fP"

.PP
Definition at line 427 of file math_util\&.h\&.
.SS "template<class T > double \fBmath::buffer\fP< T >::vmax () const\fC [inline]\fP"

.PP
Definition at line 438 of file math_util\&.h\&.
.SS "template<class T > double \fBmath::buffer\fP< T >::vmin () const\fC [inline]\fP"

.PP
Definition at line 432 of file math_util\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
