.TH "D:/tixt/corona/qdaq/lib/core/math_util.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/math_util.h
.SH SYNOPSIS
.br
.PP
\fC#include <QVector>\fP
.br
\fC#include <QExplicitlySharedDataPointer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmath::circular_buffer< T >\fP"
.br
.ti -1c
.RI "class \fBmath::running_average< T, N >\fP"
.br
.ti -1c
.RI "class \fBmath::buffer< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmath\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
