.TH "md__d_1_tixt_corona_qdaq__r_e_a_d_m_e" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__d_1_tixt_corona_qdaq__r_e_a_d_m_e \- \fBQDaq\fP 
Qdaq is a Qt-based set of tools for performing data aqcuisition (DAQ) tasks containing the following:
.PP
.IP "\(bu" 2
A hierarchy of C++ objects for various DAQ-related tasks
.IP "\(bu" 2
A set of Qt-widgets suitable for DAQ applications
.IP "\(bu" 2
A scripting interface based on Javascript and QtScript
.IP "\(bu" 2
A complete application for executing and debugging \fBQDaq\fP scripts
.PP
.PP
Documentation can be found at the \fCQDaq web-site\&.\fP 
