.TH "D:/tixt/corona/qdaq/plugins/ni-gpib/nigpib.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/plugins/ni-gpib/nigpib.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/qglobal\&.h>\fP
.br
\fC#include 'qdaqplugin\&.h'\fP
.br
\fC#include 'QDaqInterface\&.h'\fP
.br
\fC#include 'QDaqVector\&.h'\fP
.br
\fC#include <QtPlugin>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPluginFactory\fP"
.br
.ti -1c
.RI "class \fBQDaqNiGpib\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNIGPIB_EXPORT\fP   Q_DECL_IMPORT"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NIGPIB_EXPORT   Q_DECL_IMPORT"

.PP
Definition at line 10 of file nigpib\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
