.TH "Node" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (\fBQDaqObject\fP *obj, \fBNode\fP *parentItem=0)"
.br
.ti -1c
.RI "void \fBpopulate\fP ()"
.br
.ti -1c
.RI "void \fBdeleteChildren\fP ()"
.br
.ti -1c
.RI "void \fBappendChild\fP (\fBNode\fP *\fBchild\fP)"
.br
.ti -1c
.RI "void \fBinsertChild\fP (int \fBrow\fP, \fBNode\fP *\fBchild\fP)"
.br
.ti -1c
.RI "\fBNode\fP * \fBchild\fP (int \fBrow\fP)"
.br
.ti -1c
.RI "int \fBchildCount\fP () const"
.br
.ti -1c
.RI "int \fBrow\fP ()"
.br
.ti -1c
.RI "\fBNode\fP * \fBnodeOfObject\fP (const \fBQDaqObject\fP *obj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QList< \fBNode\fP * > \fBchildren\fP"
.br
.ti -1c
.RI "\fBQDaqObject\fP * \fBobjptr\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBparent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file QDaqObjectModel\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Node::Node (\fBQDaqObject\fP * obj, \fBNode\fP * parentItem = \fC0\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 21 of file QDaqObjectModel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Node::appendChild (\fBNode\fP * child)\fC [inline]\fP"

.PP
Definition at line 42 of file QDaqObjectModel\&.cpp\&.
.SS "\fBNode\fP* Node::child (int row)\fC [inline]\fP"

.PP
Definition at line 51 of file QDaqObjectModel\&.cpp\&.
.SS "int Node::childCount () const\fC [inline]\fP"

.PP
Definition at line 55 of file QDaqObjectModel\&.cpp\&.
.SS "void Node::deleteChildren ()\fC [inline]\fP"

.PP
Definition at line 34 of file QDaqObjectModel\&.cpp\&.
.SS "void Node::insertChild (int row, \fBNode\fP * child)\fC [inline]\fP"

.PP
Definition at line 46 of file QDaqObjectModel\&.cpp\&.
.SS "\fBNode\fP* Node::nodeOfObject (const \fBQDaqObject\fP * obj)\fC [inline]\fP"

.PP
Definition at line 64 of file QDaqObjectModel\&.cpp\&.
.SS "void Node::populate ()\fC [inline]\fP"

.PP
Definition at line 26 of file QDaqObjectModel\&.cpp\&.
.SS "int Node::row ()\fC [inline]\fP"

.PP
Definition at line 59 of file QDaqObjectModel\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QList<\fBNode\fP*> Node::children"

.PP
Definition at line 17 of file QDaqObjectModel\&.cpp\&.
.SS "\fBQDaqObject\fP* Node::objptr"

.PP
Definition at line 18 of file QDaqObjectModel\&.cpp\&.
.SS "\fBNode\fP* Node::parent"

.PP
Definition at line 19 of file QDaqObjectModel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
