.TH "D:/tixt/corona/qdaq/lib/gui/QConsoleWidget.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/gui/QConsoleWidget.h
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqGlobal\&.h'\fP
.br
\fC#include <QPlainTextEdit>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQConsoleWidget\fP"
.br
.RI "A simple console for python scripting\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
