.TH "D:/tixt/corona/qdaq/lib/core/qdaqh5file.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/qdaqh5file.h
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqTypes\&.h'\fP
.br
\fC#include 'QDaqObject\&.h'\fP
.br
\fC#include <hdf5\&.h>\fP
.br
\fC#include <H5Cpp\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQDaqH5File\fP"
.br
.ti -1c
.RI "class \fBh5helper\fP"
.br
.ti -1c
.RI "struct \fBh5helper::deferedPtrData\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
