.TH "D:/tixt/corona/qdaq/lib/core/QDaqH5Serialize.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/QDaqH5Serialize.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqObject\&.h'\fP
.br
\fC#include 'QDaqRoot\&.h'\fP
.br
\fC#include 'QDaqDataBuffer\&.h'\fP
.br
\fC#include 'qdaqh5file\&.h'\fP
.br
\fC#include <QDebug>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLASS_ATTR_NAME\fP   'Class'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CLASS_ATTR_NAME   'Class'"

.PP
Definition at line 11 of file QDaqH5Serialize\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
