.TH "D:/tixt/corona/qdaq/lib/core/QDaqTypes.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/QDaqTypes.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqVector\&.h'\fP
.br
\fC#include 'QDaqObject\&.h'\fP
.br
\fC#include <QScriptEngine>\fP
.br
\fC#include 'bytearrayclass\&.h'\fP
.br
\fC#include 'vectorclass\&.h'\fP
.br
\fC#include <QColor>\fP
.br
\fC#include <QPointF>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBQDaqObject\fP * \fBQDaqObjectStar\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QScriptValue \fBtoScriptValue\fP (QScriptEngine *engine, const QColor &clr)"
.br
.ti -1c
.RI "void \fBfromScriptValue\fP (const QScriptValue &obj, QColor &clr)"
.br
.ti -1c
.RI "QScriptValue \fBtoScriptValue\fP (QScriptEngine *engine, const QPointF &p)"
.br
.ti -1c
.RI "void \fBfromScriptValue\fP (const QScriptValue &obj, QPointF &p)"
.br
.ti -1c
.RI "template<class Container > QScriptValue \fBtoScriptValueContainer\fP (QScriptEngine *eng, const Container &cont)"
.br
.ti -1c
.RI "template<class Container > void \fBfromScriptValueContainer\fP (const QScriptValue &value, Container &cont)"
.br
.ti -1c
.RI "QScriptValue \fBtoScriptValue\fP (QScriptEngine *eng, const \fBQDaqObjectList\fP &L)"
.br
.ti -1c
.RI "void \fBfromScriptValue\fP (const QScriptValue &value, \fBQDaqObjectList\fP &L)"
.br
.ti -1c
.RI "QScriptValue \fBtoScriptValueQDaqObjectStar\fP (QScriptEngine *eng, const \fBQDaqObjectStar\fP &obj)"
.br
.ti -1c
.RI "void \fBfromScriptValueQDaqObjectStar\fP (const QScriptValue &value, \fBQDaqObjectStar\fP &obj)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBQDaqObject\fP* \fBQDaqObjectStar\fP"

.PP
Definition at line 109 of file QDaqTypes\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "void fromScriptValue (const QScriptValue & obj, QColor & clr)"

.PP
Definition at line 18 of file QDaqTypes\&.cpp\&.
.SS "void fromScriptValue (const QScriptValue & obj, QPointF & p)"

.PP
Definition at line 32 of file QDaqTypes\&.cpp\&.
.SS "void fromScriptValue (const QScriptValue & value, \fBQDaqObjectList\fP & L)"

.PP
Definition at line 92 of file QDaqTypes\&.cpp\&.
.SS "template<class Container > void fromScriptValueContainer (const QScriptValue & value, Container & cont)"

.PP
Definition at line 52 of file QDaqTypes\&.cpp\&.
.SS "void fromScriptValueQDaqObjectStar (const QScriptValue & value, \fBQDaqObjectStar\fP & obj)"

.PP
Definition at line 117 of file QDaqTypes\&.cpp\&.
.SS "QScriptValue toScriptValue (QScriptEngine * eng, const \fBQDaqObjectList\fP & L)"

.PP
Definition at line 81 of file QDaqTypes\&.cpp\&.
.SS "QScriptValue toScriptValue (QScriptEngine * engine, const QColor & clr)"

.PP
Definition at line 12 of file QDaqTypes\&.cpp\&.
.SS "QScriptValue toScriptValue (QScriptEngine * engine, const QPointF & p)"

.PP
Definition at line 24 of file QDaqTypes\&.cpp\&.
.SS "template<class Container > QScriptValue toScriptValueContainer (QScriptEngine * eng, const Container & cont)"

.PP
Definition at line 40 of file QDaqTypes\&.cpp\&.
.SS "QScriptValue toScriptValueQDaqObjectStar (QScriptEngine * eng, const \fBQDaqObjectStar\fP & obj)"

.PP
Definition at line 112 of file QDaqTypes\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
