.TH "QDaqObjectControllerPrivate" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqObjectControllerPrivate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddClassProperties\fP (const QMetaObject *metaObject)"
.br
.ti -1c
.RI "void \fBupdateClassProperties\fP (const QMetaObject *metaObject, bool recursive)"
.br
.ti -1c
.RI "void \fBaddDynProperties\fP ()"
.br
.ti -1c
.RI "void \fBupdateDynProperties\fP ()"
.br
.ti -1c
.RI "void \fBsaveExpandedState\fP ()"
.br
.ti -1c
.RI "void \fBrestoreExpandedState\fP ()"
.br
.ti -1c
.RI "void \fBslotValueChanged\fP (QtProperty *property, const QVariant &value)"
.br
.ti -1c
.RI "int \fBenumToInt\fP (const QMetaEnum &metaEnum, int enumValue) const"
.br
.ti -1c
.RI "int \fBintToEnum\fP (const QMetaEnum &metaEnum, int intValue) const"
.br
.ti -1c
.RI "int \fBflagToInt\fP (const QMetaEnum &metaEnum, int flagValue) const"
.br
.ti -1c
.RI "int \fBintToFlag\fP (const QMetaEnum &metaEnum, int intValue) const"
.br
.ti -1c
.RI "bool \fBisSubValue\fP (int value, int subValue) const"
.br
.ti -1c
.RI "bool \fBisPowerOf2\fP (int value) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQDaqObject\fP * \fBm_object\fP"
.br
.ti -1c
.RI "QMap< const QMetaObject *, QtProperty * > \fBm_classToProperty\fP"
.br
.ti -1c
.RI "QMap< QtProperty *, const QMetaObject * > \fBm_propertyToClass\fP"
.br
.ti -1c
.RI "QMap< QtProperty *, int > \fBm_propertyToIndex\fP"
.br
.ti -1c
.RI "QMap< const QMetaObject *, QMap< int, QtVariantProperty * > > \fBm_classToIndexToProperty\fP"
.br
.ti -1c
.RI "QMap< QtProperty *, bool > \fBm_propertyToExpanded\fP"
.br
.ti -1c
.RI "QMap< QByteArray, QtVariantProperty * > \fBm_dynPropNameToProperty\fP"
.br
.ti -1c
.RI "QMap< QtVariantProperty *, QByteArray > \fBm_propertyToDynPropName\fP"
.br
.ti -1c
.RI "QList< QtProperty * > \fBm_topLevelProperties\fP"
.br
.ti -1c
.RI "QtAbstractPropertyBrowser * \fBm_browser\fP"
.br
.ti -1c
.RI "\fBVariantManager\fP * \fBm_manager\fP"
.br
.ti -1c
.RI "\fBVariantManager\fP * \fBm_readOnlyManager\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 212 of file QDaqObjectController\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void QDaqObjectControllerPrivate::addClassProperties (const QMetaObject * metaObject)"

.PP
Definition at line 402 of file QDaqObjectController\&.cpp\&.
.SS "void QDaqObjectControllerPrivate::addDynProperties ()"

.PP
Definition at line 508 of file QDaqObjectController\&.cpp\&.
.SS "int QDaqObjectControllerPrivate::enumToInt (const QMetaEnum & metaEnum, int enumValue) const"

.PP
Definition at line 253 of file QDaqObjectController\&.cpp\&.
.SS "int QDaqObjectControllerPrivate::flagToInt (const QMetaEnum & metaEnum, int flagValue) const"

.PP
Definition at line 311 of file QDaqObjectController\&.cpp\&.
.SS "int QDaqObjectControllerPrivate::intToEnum (const QMetaEnum & metaEnum, int intValue) const"

.PP
Definition at line 268 of file QDaqObjectController\&.cpp\&.
.SS "int QDaqObjectControllerPrivate::intToFlag (const QMetaEnum & metaEnum, int intValue) const"

.PP
Definition at line 329 of file QDaqObjectController\&.cpp\&.
.SS "bool QDaqObjectControllerPrivate::isPowerOf2 (int value) const"

.PP
Definition at line 300 of file QDaqObjectController\&.cpp\&.
.SS "bool QDaqObjectControllerPrivate::isSubValue (int value, int subValue) const"

.PP
Definition at line 284 of file QDaqObjectController\&.cpp\&.
.SS "void QDaqObjectControllerPrivate::restoreExpandedState ()"

.PP
Definition at line 562 of file QDaqObjectController\&.cpp\&.
.SS "void QDaqObjectControllerPrivate::saveExpandedState ()"

.PP
Definition at line 557 of file QDaqObjectController\&.cpp\&.
.SS "void QDaqObjectControllerPrivate::slotValueChanged (QtProperty * property, const QVariant & value)"

.PP
Definition at line 567 of file QDaqObjectController\&.cpp\&.
.SS "void QDaqObjectControllerPrivate::updateClassProperties (const QMetaObject * metaObject, bool recursive)"

.PP
Definition at line 354 of file QDaqObjectController\&.cpp\&.
.SS "void QDaqObjectControllerPrivate::updateDynProperties ()"

.PP
Definition at line 389 of file QDaqObjectController\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QtAbstractPropertyBrowser* QDaqObjectControllerPrivate::m_browser"

.PP
Definition at line 248 of file QDaqObjectController\&.cpp\&.
.SS "QMap<const QMetaObject *, QMap<int, QtVariantProperty *> > QDaqObjectControllerPrivate::m_classToIndexToProperty"

.PP
Definition at line 239 of file QDaqObjectController\&.cpp\&.
.SS "QMap<const QMetaObject *, QtProperty *> QDaqObjectControllerPrivate::m_classToProperty"

.PP
Definition at line 236 of file QDaqObjectController\&.cpp\&.
.SS "QMap<QByteArray, QtVariantProperty *> QDaqObjectControllerPrivate::m_dynPropNameToProperty"

.PP
Definition at line 243 of file QDaqObjectController\&.cpp\&.
.SS "\fBVariantManager\fP* QDaqObjectControllerPrivate::m_manager"

.PP
Definition at line 249 of file QDaqObjectController\&.cpp\&.
.SS "\fBQDaqObject\fP* QDaqObjectControllerPrivate::m_object"

.PP
Definition at line 234 of file QDaqObjectController\&.cpp\&.
.SS "QMap<QtProperty *, const QMetaObject *> QDaqObjectControllerPrivate::m_propertyToClass"

.PP
Definition at line 237 of file QDaqObjectController\&.cpp\&.
.SS "QMap<QtVariantProperty *, QByteArray> QDaqObjectControllerPrivate::m_propertyToDynPropName"

.PP
Definition at line 244 of file QDaqObjectController\&.cpp\&.
.SS "QMap<QtProperty *, bool> QDaqObjectControllerPrivate::m_propertyToExpanded"

.PP
Definition at line 241 of file QDaqObjectController\&.cpp\&.
.SS "QMap<QtProperty *, int> QDaqObjectControllerPrivate::m_propertyToIndex"

.PP
Definition at line 238 of file QDaqObjectController\&.cpp\&.
.SS "\fBVariantManager\fP* QDaqObjectControllerPrivate::m_readOnlyManager"

.PP
Definition at line 250 of file QDaqObjectController\&.cpp\&.
.SS "QList<QtProperty *> QDaqObjectControllerPrivate::m_topLevelProperties"

.PP
Definition at line 246 of file QDaqObjectController\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
