.TH "QDaqScriptEngine" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqScriptEngine
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqSession\&.h>\fP
.PP
Inherits QObject\&.
.PP
Inherited by \fBQDaqSession\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsleep\fP (int ms)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqScriptEngine\fP (QObject *parent)"
.br
.ti -1c
.RI "QScriptEngine * \fBgetEngine\fP () const"
.br
.ti -1c
.RI "bool \fBcanEvaluate\fP (const QString &)"
.br
.ti -1c
.RI "bool \fBisEvaluating\fP () const"
.br
.ti -1c
.RI "bool \fBevaluate\fP (const QScriptProgram &program, QString &ret, \fBQDaqObject\fP *thisObj=0)"
.br
.ti -1c
.RI "bool \fBevaluate\fP (const QString &program, QString &ret, \fBQDaqObject\fP *thisObj=0)"
.br
.ti -1c
.RI "void \fBabortEvaluation\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QScriptEngine * \fBengine_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file QDaqSession\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqScriptEngine::QDaqScriptEngine (QObject * parent)\fC [explicit]\fP"

.PP
Definition at line 54 of file QDaqSession\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void QDaqScriptEngine::abortEvaluation ()"

.PP
Definition at line 155 of file QDaqSession\&.cpp\&.
.SS "bool QDaqScriptEngine::canEvaluate (const QString & program)"

.PP
Definition at line 147 of file QDaqSession\&.cpp\&.
.SS "bool QDaqScriptEngine::evaluate (const QScriptProgram & program, QString & ret, \fBQDaqObject\fP * thisObj = \fC0\fP)"

.PP
Definition at line 122 of file QDaqSession\&.cpp\&.
.SS "bool QDaqScriptEngine::evaluate (const QString & program, QString & ret, \fBQDaqObject\fP * thisObj = \fC0\fP)"

.PP
Definition at line 97 of file QDaqSession\&.cpp\&.
.SS "QScriptEngine* QDaqScriptEngine::getEngine () const\fC [inline]\fP"

.PP
Definition at line 36 of file QDaqSession\&.h\&.
.SS "bool QDaqScriptEngine::isEvaluating () const"

.PP
Definition at line 151 of file QDaqSession\&.cpp\&.
.SS "void QDaqScriptEngine::sleep (int ms)\fC [slot]\fP"

.PP
Definition at line 159 of file QDaqSession\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QScriptEngine* QDaqScriptEngine::engine_\fC [protected]\fP"

.PP
Definition at line 31 of file QDaqSession\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
