.TH "D:/tixt/corona/qdaq/lib/core/QDaqTypes.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/QDaqTypes.h
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqGlobal\&.h'\fP
.br
\fC#include 'QDaqVector\&.h'\fP
.br
\fC#include 'math_util\&.h'\fP
.br
\fC#include <QMetaType>\fP
.br
\fC#include <QScriptValue>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QDateTime>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBQDaqTypes\fP"
.br
.ti -1c
.RI "class \fBQDaqTimeValue\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
