.TH "D:/tixt/corona/qdaq/lib/daq/QDaqInterface.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/daq/QDaqInterface.h
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqObject\&.h'\fP
.br
\fC#include <QVector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQDaqInterface\fP"
.br
.RI "Base class of objects representing digital communications interfaces\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
