.TH "QDaqPluginManager" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqPluginManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqRoot\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef QHash< QString, const QMetaObject * > \fBobject_map_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "QList< const QMetaObject * > \fBpluginClasses\fP () const"
.br
.ti -1c
.RI "void \fBloadPlugins\fP ()"
.br
.ti -1c
.RI "void \fBloadFrom\fP (const QString &path)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBobject_map_t\fP \fBobject_map_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file QDaqRoot\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef QHash<QString, const QMetaObject*> \fBQDaqPluginManager::object_map_t\fP"

.PP
Definition at line 17 of file QDaqRoot\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void QDaqPluginManager::loadFrom (const QString & path)"

.PP
Definition at line 160 of file QDaqRoot\&.cpp\&.
.SS "void QDaqPluginManager::loadPlugins ()"

.PP
Definition at line 190 of file QDaqRoot\&.cpp\&.
.SS "QList<const QMetaObject *> QDaqPluginManager::pluginClasses () const"

.SH "Member Data Documentation"
.PP 
.SS "\fBobject_map_t\fP QDaqPluginManager::object_map_"

.PP
Definition at line 19 of file QDaqRoot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
