.TH "QDaqSession" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqSession
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqSession\&.h>\fP
.PP
Inherits \fBQDaqScriptEngine\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "QString \fBversion\fP ()"
.br
.ti -1c
.RI "void \fBquit\fP ()"
.br
.ti -1c
.RI "void \fBexec\fP (const QString &fname)"
.br
.ti -1c
.RI "void \fBprint\fP (const QString &str)"
.br
.ti -1c
.RI "void \fBwait\fP (uint ms)"
.br
.ti -1c
.RI "void \fBtextSave\fP (const QString &str, const QString &fname)"
.br
.ti -1c
.RI "QString \fBtextLoad\fP (const QString &fname)"
.br
.ti -1c
.RI "void \fBbeep\fP ()"
.br
.ti -1c
.RI "bool \fBh5write\fP (const \fBQDaqObject\fP *obj, const QString &fname)"
.br
.ti -1c
.RI "\fBQDaqObject\fP * \fBh5read\fP (const QString &fname)"
.br
.ti -1c
.RI "QString \fBpwd\fP ()"
.br
.ti -1c
.RI "bool \fBcd\fP (const QString &path)"
.br
.ti -1c
.RI "QStringList \fBdir\fP (const QStringList &filters=QStringList())"
.br
.ti -1c
.RI "QStringList \fBdir\fP (const QString &filter)"
.br
.ti -1c
.RI "bool \fBisDir\fP (const QString &name)"
.br
.ti -1c
.RI "QWidget * \fBloadUi\fP (const QString &fname)"
.br
.ti -1c
.RI "QWidget * \fBloadTopLevelUi\fP (const QString &fname, const QString &uiName)"
.br
.ti -1c
.RI "QString \fBpluginPaths\fP ()"
.br
.ti -1c
.RI "QString \fBavailableWidgets\fP ()"
.br
.ti -1c
.RI "void \fBbind\fP (\fBQDaqChannel\fP *ch, QWidget *w)"
.br
.ti -1c
.RI "void \fBbind\fP (\fBQDaqObject\fP *obj, const QString &propertyName, QWidget *w, bool readOnly=false)"
.br
.ti -1c
.RI "void \fBaddItems\fP (QComboBox *cb, const QStringList &lst)"
.br
.ti -1c
.RI "void \fBaddItems\fP (QListWidget *cb, const QStringList &lst)"
.br
.ti -1c
.RI "void \fBdeleteTab\fP (int currentIndex)"
.br
.ti -1c
.RI "int \fBinsertTab\fP (int \fBindex\fP, QWidget *page, const QString &label)"
.br
.ti -1c
.RI "void \fBdebug\fP (bool on)"
.br
.ti -1c
.RI "void \fBtic\fP ()"
.br
.ti -1c
.RI "double \fBtoc\fP ()"
.br
.ti -1c
.RI "QString \fBsystem\fP (const QString &comm)"
.br
.ti -1c
.RI "bool \fBispc\fP ()"
.br
.ti -1c
.RI "QString \fBinfo\fP (QScriptValue v)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBstdOut\fP (const QString &)"
.br
.ti -1c
.RI "void \fBstdErr\fP (const QString &)"
.br
.ti -1c
.RI "void \fBendSession\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqSession\fP (QObject *parent=0)"
.br
.RI "\fBQDaqSession::QDaqSession\fP\&. "
.ti -1c
.RI "virtual \fB~QDaqSession\fP (void)"
.br
.ti -1c
.RI "void \fBevaluate\fP (const QString &program)"
.br
.ti -1c
.RI "void \fBabortEvaluation\fP ()"
.br
.ti -1c
.RI "int \fBindex\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBnextAvailableIndex\fP ()"
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBlog_in\fP (const QString &str)"
.br
.ti -1c
.RI "void \fBlog_out\fP (const QString &str)"
.br
.ti -1c
.RI "void \fBlog_err\fP (const QString &str)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBlog__\fP (int fd, const QString &str)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QScriptEngineDebugger * \fBdebugger_\fP"
.br
.ti -1c
.RI "QTimer * \fBwait_timer_\fP"
.br
.ti -1c
.RI "bool \fBwait_aborted_\fP"
.br
.ti -1c
.RI "QElapsedTimer \fBwatch_\fP"
.br
.ti -1c
.RI "int \fBidx_\fP"
.br
.ti -1c
.RI "\fBQDaqLogFile\fP * \fBlogFile_\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static QSet< int > \fBidx_set\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file QDaqSession\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqSession::QDaqSession (QObject * parent = \fC0\fP)"

.PP
\fBQDaqSession::QDaqSession\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIparent\fP 
.RE
.PP

.PP
Definition at line 173 of file QDaqSession\&.cpp\&.
.SS "QDaqSession::~QDaqSession (void)\fC [virtual]\fP"

.PP
Definition at line 206 of file QDaqSession\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void QDaqSession::abortEvaluation ()"

.PP
Definition at line 247 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::addItems (QComboBox * cb, const QStringList & lst)\fC [slot]\fP"

.PP
Definition at line 522 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::addItems (QListWidget * cb, const QStringList & lst)\fC [slot]\fP"

.PP
Definition at line 527 of file QDaqSession\&.cpp\&.
.SS "QString QDaqSession::availableWidgets ()\fC [slot]\fP"

.PP
Definition at line 465 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::beep ()\fC [slot]\fP"

.PP
Definition at line 310 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::bind (\fBQDaqChannel\fP * ch, QWidget * w)\fC [slot]\fP"

.PP
Definition at line 470 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::bind (\fBQDaqObject\fP * obj, const QString & propertyName, QWidget * w, bool readOnly = \fCfalse\fP)\fC [slot]\fP"

.PP
Definition at line 479 of file QDaqSession\&.cpp\&.
.SS "bool QDaqSession::cd (const QString & path)\fC [slot]\fP"

.PP
Definition at line 325 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::debug (bool on)\fC [slot]\fP"

.PP
Definition at line 346 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::deleteTab (int currentIndex)\fC [slot]\fP"

.PP
Definition at line 547 of file QDaqSession\&.cpp\&.
.SS "QStringList QDaqSession::dir (const QString & filter)\fC [slot]\fP"

.PP
Definition at line 337 of file QDaqSession\&.cpp\&.
.SS "QStringList QDaqSession::dir (const QStringList & filters = \fCQStringList()\fP)\fC [slot]\fP"

.PP
Definition at line 333 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::endSession ()\fC [signal]\fP"

.SS "void QDaqSession::evaluate (const QString & program)"

.PP
Definition at line 224 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::exec (const QString & fname)\fC [slot]\fP"

.PP
Definition at line 253 of file QDaqSession\&.cpp\&.
.SS "\fBQDaqObject\fP * QDaqSession::h5read (const QString & fname)\fC [slot]\fP"

.PP
Definition at line 390 of file QDaqSession\&.cpp\&.
.SS "bool QDaqSession::h5write (const \fBQDaqObject\fP * obj, const QString & fname)\fC [slot]\fP"

.PP
Definition at line 382 of file QDaqSession\&.cpp\&.
.SS "int QDaqSession::index () const\fC [inline]\fP"

.PP
Definition at line 74 of file QDaqSession\&.h\&.
.SS "QString QDaqSession::info (QScriptValue v)\fC [slot]\fP"

.PP
Definition at line 563 of file QDaqSession\&.cpp\&.
.SS "int QDaqSession::insertTab (int index, QWidget * page, const QString & label)\fC [slot]\fP"

.PP
Definition at line 532 of file QDaqSession\&.cpp\&.
.SS "bool QDaqSession::isDir (const QString & name)\fC [slot]\fP"

.PP
Definition at line 341 of file QDaqSession\&.cpp\&.
.SS "bool QDaqSession::ispc ()\fC [inline]\fP, \fC [slot]\fP"

.PP
Definition at line 123 of file QDaqSession\&.h\&.
.SS "QWidget * QDaqSession::loadTopLevelUi (const QString & fname, const QString & uiName)\fC [slot]\fP"

.PP
Definition at line 425 of file QDaqSession\&.cpp\&.
.SS "QWidget * QDaqSession::loadUi (const QString & fname)\fC [slot]\fP"

.PP
Definition at line 400 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::log__ (int fd, const QString & str)\fC [protected]\fP"

.PP
Definition at line 362 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::log_err (const QString & str)\fC [inline]\fP, \fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 138 of file QDaqSession\&.h\&.
.SS "void QDaqSession::log_in (const QString & str)\fC [inline]\fP, \fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 136 of file QDaqSession\&.h\&.
.SS "void QDaqSession::log_out (const QString & str)\fC [inline]\fP, \fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 137 of file QDaqSession\&.h\&.
.SS "int QDaqSession::nextAvailableIndex ()\fC [static]\fP"

.PP
Definition at line 217 of file QDaqSession\&.cpp\&.
.SS "QString QDaqSession::pluginPaths ()\fC [slot]\fP"

.PP
Definition at line 460 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::print (const QString & str)\fC [slot]\fP"

.PP
Definition at line 281 of file QDaqSession\&.cpp\&.
.SS "QString QDaqSession::pwd ()\fC [slot]\fP"

.PP
Definition at line 320 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::quit ()\fC [slot]\fP"

.PP
Definition at line 315 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::stdErr (const QString &)\fC [signal]\fP"

.SS "void QDaqSession::stdOut (const QString &)\fC [signal]\fP"

.SS "QString QDaqSession::system (const QString & comm)\fC [slot]\fP"

.PP
Definition at line 351 of file QDaqSession\&.cpp\&.
.SS "QString QDaqSession::textLoad (const QString & fname)\fC [slot]\fP"

.PP
Definition at line 297 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::textSave (const QString & str, const QString & fname)\fC [slot]\fP"

.PP
Definition at line 286 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::tic ()\fC [inline]\fP, \fC [slot]\fP"

.PP
Definition at line 117 of file QDaqSession\&.h\&.
.SS "double QDaqSession::toc ()\fC [inline]\fP, \fC [slot]\fP"

.PP
Definition at line 118 of file QDaqSession\&.h\&.
.SS "QString QDaqSession::version ()\fC [slot]\fP"

.PP
Definition at line 651 of file QDaqSession\&.cpp\&.
.SS "void QDaqSession::wait (uint ms)\fC [slot]\fP"

.PP
Definition at line 237 of file QDaqSession\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QScriptEngineDebugger* QDaqSession::debugger_\fC [protected]\fP"

.PP
Definition at line 57 of file QDaqSession\&.h\&.
.SS "int QDaqSession::idx_\fC [protected]\fP"

.PP
Definition at line 63 of file QDaqSession\&.h\&.
.SS "QSet< int > QDaqSession::idx_set\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 65 of file QDaqSession\&.h\&.
.SS "\fBQDaqLogFile\fP* QDaqSession::logFile_\fC [protected]\fP"

.PP
Definition at line 67 of file QDaqSession\&.h\&.
.SS "bool QDaqSession::wait_aborted_\fC [protected]\fP"

.PP
Definition at line 59 of file QDaqSession\&.h\&.
.SS "QTimer* QDaqSession::wait_timer_\fC [protected]\fP"

.PP
Definition at line 58 of file QDaqSession\&.h\&.
.SS "QElapsedTimer QDaqSession::watch_\fC [protected]\fP"

.PP
Definition at line 60 of file QDaqSession\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
