.TH "QDaqConsole" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqConsole
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqConsole\&.h>\fP
.PP
Inherits \fBQConsoleWidget\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBendSession\fP ()"
.br
.ti -1c
.RI "void \fBflush\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqConsole\fP (\fBQDaqSession\fP *s, QWidget *parent=0)"
.br
.ti -1c
.RI "virtual \fB~QDaqConsole\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBexec\fP (const QString &code)"
.br
.ti -1c
.RI "bool \fBcanEvaluate\fP (const QString &code)"
.br
.ti -1c
.RI "QStringList \fBintrospection\fP (const QString &lookup)"
.br
.ti -1c
.RI "virtual void \fBcloseEvent\fP (QCloseEvent *event)"
.br
.ti -1c
.RI "virtual void \fBkeyPressEvent\fP (QKeyEvent *e)"
.br
.RI "derived key press event "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file QDaqConsole\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqConsole::QDaqConsole (\fBQDaqSession\fP * s, QWidget * parent = \fC0\fP)"

.PP
Definition at line 18 of file QDaqConsole\&.cpp\&.
.SS "QDaqConsole::~QDaqConsole ()\fC [virtual]\fP"

.PP
Definition at line 45 of file QDaqConsole\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool QDaqConsole::canEvaluate (const QString & code)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBQConsoleWidget\fP\&.
.PP
Definition at line 54 of file QDaqConsole\&.cpp\&.
.SS "void QDaqConsole::closeEvent (QCloseEvent * event)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 65 of file QDaqConsole\&.cpp\&.
.SS "void QDaqConsole::endSession ()\fC [slot]\fP"

.PP
Definition at line 59 of file QDaqConsole\&.cpp\&.
.SS "void QDaqConsole::exec (const QString & code)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBQConsoleWidget\fP\&.
.PP
Definition at line 50 of file QDaqConsole\&.cpp\&.
.SS "void QDaqConsole::flush ()\fC [inline]\fP, \fC [slot]\fP"

.PP
Definition at line 25 of file QDaqConsole\&.h\&.
.SS "QStringList QDaqConsole::introspection (const QString & lookup)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBQConsoleWidget\fP\&.
.PP
Definition at line 129 of file QDaqConsole\&.cpp\&.
.SS "void QDaqConsole::keyPressEvent (QKeyEvent * e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
derived key press event 
.PP
Reimplemented from \fBQConsoleWidget\fP\&.
.PP
Definition at line 105 of file QDaqConsole\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
