.TH "QDaqIDE" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqIDE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqIde\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqIDE\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcloseEvent\fP (QCloseEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file QDaqIde\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqIDE::QDaqIDE ()"

.PP
Definition at line 24 of file QDaqIde\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void QDaqIDE::closeEvent (QCloseEvent * event)\fC [protected]\fP"

.PP
Definition at line 50 of file QDaqIde\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
