.TH "D:/tixt/corona/qdaq/lib/core/QDaqJob.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/QDaqJob.h
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqObject\&.h'\fP
.br
\fC#include 'math_util\&.h'\fP
.br
\fC#include 'qtimerthread\&.h'\fP
.br
\fC#include <QPointer>\fP
.br
\fC#include <QAtomicInt>\fP
.br
\fC#include <QElapsedTimer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQDaqJob\fP"
.br
.ti -1c
.RI "class \fBQDaqJob::JobList\fP"
.br
.ti -1c
.RI "class \fBQDaqJob::JobLocker\fP"
.br
.ti -1c
.RI "class \fBQDaqLoop\fP"
.br
.RI "A class encapsulating a software loop\&. "
.ti -1c
.RI "class \fBQDaqLoop::LoopTimerThread\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
