.TH "QDaqObjectController" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqObjectController
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqObjectController\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBupdateProperties\fP ()"
.br
.ti -1c
.RI "void \fBupdateDynamicProperties\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqObjectController\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~QDaqObjectController\fP ()"
.br
.ti -1c
.RI "void \fBsetObject\fP (\fBQDaqObject\fP *\fBobject\fP)"
.br
.ti -1c
.RI "\fBQDaqObject\fP * \fBobject\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file QDaqObjectController\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqObjectController::QDaqObjectController (QWidget * parent = \fC0\fP)"

.PP
Definition at line 600 of file QDaqObjectController\&.cpp\&.
.SS "QDaqObjectController::~QDaqObjectController ()"

.PP
Definition at line 640 of file QDaqObjectController\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBQDaqObject\fP * QDaqObjectController::object () const"

.PP
Definition at line 670 of file QDaqObjectController\&.cpp\&.
.SS "void QDaqObjectController::setObject (\fBQDaqObject\fP * object)"

.PP
Definition at line 645 of file QDaqObjectController\&.cpp\&.
.SS "void QDaqObjectController::updateDynamicProperties ()\fC [slot]\fP"

.PP
Definition at line 680 of file QDaqObjectController\&.cpp\&.
.SS "void QDaqObjectController::updateProperties ()\fC [slot]\fP"

.PP
Definition at line 675 of file QDaqObjectController\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
