.TH "QDaqPlotWidgetPlugin" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqPlotWidgetPlugin
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qdaqplotwidgetplugin\&.h>\fP
.PP
Inherits QObject, and QDesignerCustomWidgetInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqPlotWidgetPlugin\fP (QObject *parent=0)"
.br
.ti -1c
.RI "bool \fBisContainer\fP () const"
.br
.ti -1c
.RI "bool \fBisInitialized\fP () const"
.br
.ti -1c
.RI "QIcon \fBicon\fP () const"
.br
.ti -1c
.RI "QString \fBdomXml\fP () const"
.br
.ti -1c
.RI "QString \fBgroup\fP () const"
.br
.ti -1c
.RI "QString \fBincludeFile\fP () const"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "QString \fBtoolTip\fP () const"
.br
.ti -1c
.RI "QString \fBwhatsThis\fP () const"
.br
.ti -1c
.RI "QWidget * \fBcreateWidget\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBinitialize\fP (QDesignerFormEditorInterface *core)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file qdaqplotwidgetplugin\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqPlotWidgetPlugin::QDaqPlotWidgetPlugin (QObject * parent = \fC0\fP)"

.PP
Definition at line 7 of file qdaqplotwidgetplugin\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QWidget * QDaqPlotWidgetPlugin::createWidget (QWidget * parent)"

.PP
Definition at line 28 of file qdaqplotwidgetplugin\&.cpp\&.
.SS "QString QDaqPlotWidgetPlugin::domXml () const"

.PP
Definition at line 63 of file qdaqplotwidgetplugin\&.cpp\&.
.SS "QString QDaqPlotWidgetPlugin::group () const"

.PP
Definition at line 38 of file qdaqplotwidgetplugin\&.cpp\&.
.SS "QIcon QDaqPlotWidgetPlugin::icon () const"

.PP
Definition at line 43 of file qdaqplotwidgetplugin\&.cpp\&.
.SS "QString QDaqPlotWidgetPlugin::includeFile () const"

.PP
Definition at line 68 of file qdaqplotwidgetplugin\&.cpp\&.
.SS "void QDaqPlotWidgetPlugin::initialize (QDesignerFormEditorInterface * core)"

.PP
Definition at line 13 of file qdaqplotwidgetplugin\&.cpp\&.
.SS "bool QDaqPlotWidgetPlugin::isContainer () const"

.PP
Definition at line 58 of file qdaqplotwidgetplugin\&.cpp\&.
.SS "bool QDaqPlotWidgetPlugin::isInitialized () const"

.PP
Definition at line 23 of file qdaqplotwidgetplugin\&.cpp\&.
.SS "QString QDaqPlotWidgetPlugin::name () const"

.PP
Definition at line 33 of file qdaqplotwidgetplugin\&.cpp\&.
.SS "QString QDaqPlotWidgetPlugin::toolTip () const"

.PP
Definition at line 48 of file qdaqplotwidgetplugin\&.cpp\&.
.SS "QString QDaqPlotWidgetPlugin::whatsThis () const"

.PP
Definition at line 53 of file qdaqplotwidgetplugin\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
