.TH "QDaqConsoleTabPlugin" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqConsoleTabPlugin
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qdaqconsoletabplugin\&.h>\fP
.PP
Inherits QObject, and QDesignerCustomWidgetInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqConsoleTabPlugin\fP (QObject *parent=0)"
.br
.ti -1c
.RI "bool \fBisContainer\fP () const"
.br
.ti -1c
.RI "bool \fBisInitialized\fP () const"
.br
.ti -1c
.RI "QIcon \fBicon\fP () const"
.br
.ti -1c
.RI "QString \fBdomXml\fP () const"
.br
.ti -1c
.RI "QString \fBgroup\fP () const"
.br
.ti -1c
.RI "QString \fBincludeFile\fP () const"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "QString \fBtoolTip\fP () const"
.br
.ti -1c
.RI "QString \fBwhatsThis\fP () const"
.br
.ti -1c
.RI "QWidget * \fBcreateWidget\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBinitialize\fP (QDesignerFormEditorInterface *core)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file qdaqconsoletabplugin\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqConsoleTabPlugin::QDaqConsoleTabPlugin (QObject * parent = \fC0\fP)"

.PP
Definition at line 6 of file qdaqconsoletabplugin\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QWidget * QDaqConsoleTabPlugin::createWidget (QWidget * parent)"

.PP
Definition at line 28 of file qdaqconsoletabplugin\&.cpp\&.
.SS "QString QDaqConsoleTabPlugin::domXml () const"

.PP
Definition at line 63 of file qdaqconsoletabplugin\&.cpp\&.
.SS "QString QDaqConsoleTabPlugin::group () const"

.PP
Definition at line 38 of file qdaqconsoletabplugin\&.cpp\&.
.SS "QIcon QDaqConsoleTabPlugin::icon () const"

.PP
Definition at line 43 of file qdaqconsoletabplugin\&.cpp\&.
.SS "QString QDaqConsoleTabPlugin::includeFile () const"

.PP
Definition at line 68 of file qdaqconsoletabplugin\&.cpp\&.
.SS "void QDaqConsoleTabPlugin::initialize (QDesignerFormEditorInterface * core)"

.PP
Definition at line 13 of file qdaqconsoletabplugin\&.cpp\&.
.SS "bool QDaqConsoleTabPlugin::isContainer () const"

.PP
Definition at line 58 of file qdaqconsoletabplugin\&.cpp\&.
.SS "bool QDaqConsoleTabPlugin::isInitialized () const"

.PP
Definition at line 23 of file qdaqconsoletabplugin\&.cpp\&.
.SS "QString QDaqConsoleTabPlugin::name () const"

.PP
Definition at line 33 of file qdaqconsoletabplugin\&.cpp\&.
.SS "QString QDaqConsoleTabPlugin::toolTip () const"

.PP
Definition at line 48 of file qdaqconsoletabplugin\&.cpp\&.
.SS "QString QDaqConsoleTabPlugin::whatsThis () const"

.PP
Definition at line 53 of file qdaqconsoletabplugin\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
