.TH "D:/tixt/corona/qdaq/lib/core/QDaqDataBuffer.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/QDaqDataBuffer.h
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqVector\&.h'\fP
.br
\fC#include 'QDaqJob\&.h'\fP
.br
\fC#include <QPointer>\fP
.br
\fC#include <QSemaphore>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQDaqDataBuffer\fP"
.br
.RI "A class that provides storage of channel or other data\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
