.TH "QDaqTimeValue" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqTimeValue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqTypes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqTimeValue\fP ()"
.br
.RI "default constructor "
.ti -1c
.RI "\fBQDaqTimeValue\fP (double d)"
.br
.RI "construct from double "
.ti -1c
.RI "\fBQDaqTimeValue\fP (const \fBQDaqTimeValue\fP &rhs)"
.br
.RI "copy constructor "
.ti -1c
.RI "\fBQDaqTimeValue\fP & \fBoperator=\fP (const \fBQDaqTimeValue\fP &rhs)"
.br
.RI "copy operator "
.ti -1c
.RI "\fBoperator double\fP ()"
.br
.RI "type conversion operator to double "
.ti -1c
.RI "\fBoperator QDateTime\fP ()"
.br
.RI "convert to QDateTime "
.ti -1c
.RI "QString \fBtoString\fP ()"
.br
.RI "convert to string "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBQDaqTimeValue\fP \fBnow\fP ()"
.br
.RI "return current time in \fBQDaqTimeValue\fP format "
.in -1c
.SH "Detailed Description"
.PP 
Time representation in \fBQDaq\fP\&.
.PP
Time is represented internaly as a double number corresponding to seconds since 1 Jan 1970 as returned by the POSIX ftime function\&. It is recorded with millisecond resolution\&. 
.PP
Definition at line 51 of file QDaqTypes\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqTimeValue::QDaqTimeValue ()\fC [inline]\fP"

.PP
default constructor 
.PP
Definition at line 57 of file QDaqTypes\&.h\&.
.SS "QDaqTimeValue::QDaqTimeValue (double d)\fC [inline]\fP, \fC [explicit]\fP"

.PP
construct from double 
.PP
Definition at line 60 of file QDaqTypes\&.h\&.
.SS "QDaqTimeValue::QDaqTimeValue (const \fBQDaqTimeValue\fP & rhs)\fC [inline]\fP"

.PP
copy constructor 
.PP
Definition at line 63 of file QDaqTypes\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBQDaqTimeValue\fP QDaqTimeValue::now ()\fC [inline]\fP, \fC [static]\fP"

.PP
return current time in \fBQDaqTimeValue\fP format 
.PP
Definition at line 83 of file QDaqTypes\&.h\&.
.SS "QDaqTimeValue::operator double ()\fC [inline]\fP"

.PP
type conversion operator to double 
.PP
Definition at line 74 of file QDaqTypes\&.h\&.
.SS "QDaqTimeValue::operator QDateTime ()\fC [inline]\fP"

.PP
convert to QDateTime 
.PP
Definition at line 77 of file QDaqTypes\&.h\&.
.SS "\fBQDaqTimeValue\fP& QDaqTimeValue::operator= (const \fBQDaqTimeValue\fP & rhs)\fC [inline]\fP"

.PP
copy operator 
.PP
Definition at line 67 of file QDaqTypes\&.h\&.
.SS "QString QDaqTimeValue::toString ()\fC [inline]\fP"

.PP
convert to string 
.PP
Definition at line 89 of file QDaqTypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
