.TH "QDaqLed" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqLed
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqLed\&.h>\fP
.PP
Inherits \fBKLed\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetState\fP (bool f)"
.br
.ti -1c
.RI "bool \fBisOn\fP () const"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqLed\fP (QWidget *parent=0)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file QDaqLed\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqLed::QDaqLed (QWidget * parent = \fC0\fP)"

.PP
Definition at line 3 of file QDaqLed\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool QDaqLed::isOn () const\fC [inline]\fP, \fC [slot]\fP"

.PP
Definition at line 17 of file QDaqLed\&.h\&.
.SS "void QDaqLed::setState (bool f)\fC [slot]\fP"

.PP
Definition at line 8 of file QDaqLed\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
