.TH "qdaq_app" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qdaq_app \- qdaq 
\fBqdaq\fP is an application that can be used for both developing and running \fBQDaq\fP scripts\&.
.PP
It provides basically a script interpreter that evaluates the scripts\&. Evaluation can be done interactively on a console window or in the background\&.
.PP
\fBQDaq\fP scripts can create windows (see the functions loadWidget and loadTopLevelWidget) and thus a complete windowed application can be made solely with script code\&. Then \fBqdaq\fP can used to run the script application\&.
.PP
A very helpfull tool for developing \fBQDaq\fP script applications is the \fBQDaq IDE\fP\&. Typically script development will be done with the IDE, so that the developer can browse all objects and their properties and test commands and procedures\&. Once the application script is finalized, it may be passed to \fBqdaq\fP at the command line and the application starts like a normal windowed application\&.
.SH "Running qdaq"
.PP
You can run qdaq either from the command line or by clicking the application icon\&.
.PP
Giving the option --help at the command line displays the following
.PP
.PP
.nf
$ qdaq --help
Usage: qdaq [options] script

Options:
  -c, --console  Start a script console window\&.
  -d, --debug    Start in script-debugging mode\&.
  -h, --help     Displays this help\&.
  -v, --version  Displays version information\&.

Arguments:
  script         A \&.js script to run at startup\&.
.fi
.PP
.PP
If the program is invoked without any options the \fBQDaq IDE\fP is started\&.
.PP
If it is invoked with a script file as argument, then the script file is parsed and executed\&. If the script creates application windows, then qdaq proceeds as a normal window application until the user closes the window\&.
.PP
All application windows created by \fBQDaq\fP have a special menu which can be invoked by pressing Ctrl-F8\&. From the menu one can either open the \fBQDaq IDE\fP or just a script console\&. This may be used for debugging an application or running some script command\&. All qdaq objects are accesible from the IDE or console\&.
.SH "QDaq IDE"
.PP
\fBQDaq\fP includes a simple IDE (Integrated Development Environment)\&.
.PP
QDaq IDE window
.PP
The IDE provides the following features:
.IP "\(bu" 2
Script console for interactive command control of \fBQDaq\fP objects, with syntax highlighting (TODO) and object introspection
.IP "\(bu" 2
Script editor with syntax highlighting
.IP "\(bu" 2
\fBQDaq\fP object/property browser which allows on-line editing of object properties
.IP "\(bu" 2
\fBQDaq\fP window browser (TODO)
.IP "\(bu" 2
\fBQDaqChannel\fP viewer - display of all channels (TODO)
.IP "\(bu" 2
Error queue browser 
.PP

