.TH "D:/tixt/corona/qdaq/lib/gui/QDaqDelegates.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/gui/QDaqDelegates.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqDelegates\&.h'\fP
.br
\fC#include 'QDaqChannel\&.h'\fP
.br
\fC#include <QMetaProperty>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QLCDNumber>\fP
.br
\fC#include <qwt_thermo\&.h>\fP
.br
\fC#include 'QDaqLed\&.h'\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QComboBox>\fP
.br
\fC#include <QSpinBox>\fP
.br
\fC#include <QDoubleSpinBox>\fP
.br
\fC#include <QAbstractSlider>\fP
.br
\fC#include <QAbstractButton>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
