.TH "QDaqFOPDT" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqFOPDT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qdaqfopdt\&.h>\fP
.PP
Inherits \fBQDaqFilter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Q_INVOKABLE \fBQDaqFOPDT\fP (const QString &name)"
.br
.ti -1c
.RI "virtual int \fBnInputChannels\fP () const"
.br
.ti -1c
.RI "virtual int \fBnOutputChannels\fP () const"
.br
.ti -1c
.RI "double \fBkp\fP () const"
.br
.ti -1c
.RI "uint \fBtp\fP () const"
.br
.ti -1c
.RI "uint \fBtd\fP () const"
.br
.ti -1c
.RI "void \fBsetKp\fP (double k)"
.br
.ti -1c
.RI "void \fBsetTp\fP (uint t)"
.br
.ti -1c
.RI "void \fBsetTd\fP (uint t)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBfilterinit\fP ()"
.br
.ti -1c
.RI "virtual bool \fBfilterfunc\fP (const double *vin, double *vout)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBkp\fP"
.br
.ti -1c
.RI "uint \fBtp\fP"
.br
.ti -1c
.RI "uint \fBtd\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file qdaqfopdt\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqFOPDT::QDaqFOPDT (const QString & name)\fC [explicit]\fP"

.PP
Definition at line 3 of file qdaqfopdt\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool QDaqFOPDT::filterfunc (const double * vin, double * vout)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBQDaqFilter\fP\&.
.PP
Definition at line 23 of file qdaqfopdt\&.cpp\&.
.SS "bool QDaqFOPDT::filterinit ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBQDaqFilter\fP\&.
.PP
Definition at line 12 of file qdaqfopdt\&.cpp\&.
.SS "double QDaqFOPDT::kp () const\fC [inline]\fP"

.PP
Definition at line 35 of file qdaqfopdt\&.h\&.
.SS "virtual int QDaqFOPDT::nInputChannels () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBQDaqFilter\fP\&.
.PP
Definition at line 33 of file qdaqfopdt\&.h\&.
.SS "virtual int QDaqFOPDT::nOutputChannels () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBQDaqFilter\fP\&.
.PP
Definition at line 34 of file qdaqfopdt\&.h\&.
.SS "void QDaqFOPDT::setKp (double k)"

.PP
Definition at line 34 of file qdaqfopdt\&.cpp\&.
.SS "void QDaqFOPDT::setTd (uint t)"

.PP
Definition at line 46 of file qdaqfopdt\&.cpp\&.
.SS "void QDaqFOPDT::setTp (uint t)"

.PP
Definition at line 40 of file qdaqfopdt\&.cpp\&.
.SS "uint QDaqFOPDT::td () const\fC [inline]\fP"

.PP
Definition at line 37 of file qdaqfopdt\&.h\&.
.SS "uint QDaqFOPDT::tp () const\fC [inline]\fP"

.PP
Definition at line 36 of file qdaqfopdt\&.h\&.
.SH "Property Documentation"
.PP 
.SS "double QDaqFOPDT::kp\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file qdaqfopdt\&.h\&.
.SS "uint QDaqFOPDT::td\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file qdaqfopdt\&.h\&.
.SS "uint QDaqFOPDT::tp\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file qdaqfopdt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
