.TH "D:/tixt/corona/qdaq/lib/core/QDaqLogFile.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/QDaqLogFile.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqLogFile\&.h'\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QDate>\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include 'QDaqObject\&.h'\fP
.br
\fC#include 'QDaqRoot\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
