.TH "QDaqObjectModel" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqObjectModel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqObjectModel\&.h>\fP
.PP
Inherits QAbstractItemModel\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBNumColumns\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqObjectModel\fP (QObject *\fBparent\fP=0)"
.br
.ti -1c
.RI "virtual \fB~QDaqObjectModel\fP ()"
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override"
.br
.ti -1c
.RI "QModelIndex \fBindex\fP (int row, int column, const QModelIndex &\fBparent\fP=QModelIndex()) const override"
.br
.ti -1c
.RI "QModelIndex \fBparent\fP (const QModelIndex &\fBindex\fP) const override"
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &\fBparent\fP=QModelIndex()) const override"
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &\fBparent\fP=QModelIndex()) const override"
.br
.ti -1c
.RI "bool \fBhasChildren\fP (const QModelIndex &\fBparent\fP=QModelIndex()) const override"
.br
.ti -1c
.RI "bool \fBcanFetchMore\fP (const QModelIndex &\fBparent\fP) const override"
.br
.ti -1c
.RI "void \fBfetchMore\fP (const QModelIndex &\fBparent\fP) override"
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &\fBindex\fP, int role=Qt::DisplayRole) const override"
.br
.ti -1c
.RI "QModelIndex \fBindex\fP (const \fBQDaqObject\fP *, int column=0) const"
.br
.ti -1c
.RI "QModelIndex \fBindex\fP (const QString &path, int column=0) const"
.br
.ti -1c
.RI "\fBQDaqObject\fP * \fBobjectAt\fP (const QModelIndex &\fBindex\fP) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBQDaqObjectModel\fP represents the \fBQDaq\fP object tree as a Qt item model\&.
.PP
This class enables the visual representation of the \fBQDaq\fP object tree in Qt's model/view classes\&.
.PP
The class is just a wrapper around the \fBQDaqObject\fP hierarchy\&. No extra data is generated for the class\&. 
.PP
Definition at line 19 of file QDaqObjectModel\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINumColumns \fP\fP
.PP
Definition at line 26 of file QDaqObjectModel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqObjectModel::QDaqObjectModel (QObject * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 76 of file QDaqObjectModel\&.cpp\&.
.SS "QDaqObjectModel::~QDaqObjectModel ()\fC [virtual]\fP"

.PP
Definition at line 88 of file QDaqObjectModel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool QDaqObjectModel::canFetchMore (const QModelIndex & parent) const\fC [override]\fP"

.PP
Definition at line 202 of file QDaqObjectModel\&.cpp\&.
.SS "int QDaqObjectModel::columnCount (const QModelIndex & parent = \fCQModelIndex()\fP) const\fC [override]\fP"

.PP
Definition at line 184 of file QDaqObjectModel\&.cpp\&.
.SS "QVariant QDaqObjectModel::data (const QModelIndex & index, int role = \fCQt::DisplayRole\fP) const\fC [override]\fP"

.PP
Definition at line 226 of file QDaqObjectModel\&.cpp\&.
.SS "void QDaqObjectModel::fetchMore (const QModelIndex & parent)\fC [override]\fP"

.PP
Definition at line 209 of file QDaqObjectModel\&.cpp\&.
.SS "bool QDaqObjectModel::hasChildren (const QModelIndex & parent = \fCQModelIndex()\fP) const\fC [override]\fP"

.PP
Definition at line 189 of file QDaqObjectModel\&.cpp\&.
.SS "QVariant QDaqObjectModel::headerData (int section, Qt::Orientation orientation, int role = \fCQt::DisplayRole\fP) const\fC [override]\fP"

.PP
Definition at line 95 of file QDaqObjectModel\&.cpp\&.
.SS "QModelIndex QDaqObjectModel::index (const \fBQDaqObject\fP * obj, int column = \fC0\fP) const"

.PP
Definition at line 300 of file QDaqObjectModel\&.cpp\&.
.SS "QModelIndex QDaqObjectModel::index (const QString & path, int column = \fC0\fP) const"

.PP
Definition at line 316 of file QDaqObjectModel\&.cpp\&.
.SS "QModelIndex QDaqObjectModel::index (int row, int column, const QModelIndex & parent = \fCQModelIndex()\fP) const\fC [override]\fP"

.PP
Definition at line 127 of file QDaqObjectModel\&.cpp\&.
.SS "\fBQDaqObject\fP * QDaqObjectModel::objectAt (const QModelIndex & index) const"

.PP
Definition at line 322 of file QDaqObjectModel\&.cpp\&.
.SS "QModelIndex QDaqObjectModel::parent (const QModelIndex & index) const\fC [override]\fP"

.PP
Definition at line 146 of file QDaqObjectModel\&.cpp\&.
.SS "int QDaqObjectModel::rowCount (const QModelIndex & parent = \fCQModelIndex()\fP) const\fC [override]\fP"

.PP
Definition at line 171 of file QDaqObjectModel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
