.TH "D:/tixt/corona/qdaq/lib/gui/QDaqPlotWidget.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/gui/QDaqPlotWidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqPlotWidget\&.h'\fP
.br
\fC#include 'QDaqTypes\&.h'\fP
.br
\fC#include <QCloseEvent>\fP
.br
\fC#include <QCoreApplication>\fP
.br
\fC#include <QSet>\fP
.br
\fC#include <QRegularExpression>\fP
.br
\fC#include <qwt_plot_curve\&.h>\fP
.br
\fC#include <qwt_series_data\&.h>\fP
.br
\fC#include <qwt_symbol\&.h>\fP
.br
\fC#include <qwt_scale_draw\&.h>\fP
.br
\fC#include <qwt_plot_grid\&.h>\fP
.br
\fC#include <qwt_scale_engine\&.h>\fP
.br
\fC#include <qwt_plot_zoomer\&.h>\fP
.br
\fC#include <qwt_plot_panner\&.h>\fP
.br
\fC#include <qwt_plot_picker\&.h>\fP
.br
\fC#include <qwt_math\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFormattedPicker\fP"
.br
.ti -1c
.RI "class \fBZoomer\fP"
.br
.ti -1c
.RI "class \fBTimeScaleDraw\fP"
.br
.ti -1c
.RI "class \fBSciScaleDraw\fP"
.br
.ti -1c
.RI "class \fBTimeScaleEngine\fP"
.br
.ti -1c
.RI "class \fBQDaqPlotData\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
