.TH "QDaqJob::JobLocker" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqJob::JobLocker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqJob\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJobLocker\fP (\fBQDaqJob\fP *aj)"
.br
.ti -1c
.RI "\fB~JobLocker\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 182 of file QDaqJob\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqJob::JobLocker::JobLocker (\fBQDaqJob\fP * aj)\fC [inline]\fP"

.PP
Definition at line 186 of file QDaqJob\&.h\&.
.SS "QDaqJob::JobLocker::~JobLocker ()\fC [inline]\fP"

.PP
Definition at line 187 of file QDaqJob\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
