.TH "QDaqPlotWidget" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqPlotWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqPlotWidget\&.h>\fP
.PP
Inherits QwtPlot\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBplot\fP (const \fBQDaqVector\fP &x, const \fBQDaqVector\fP &y, const QString &attr, const QColor &clr=QColor())"
.br
.ti -1c
.RI "void \fBplot\fP (const \fBQDaqVector\fP &x, const \fBQDaqVector\fP &y, const QColor &clr=QColor())"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqPlotWidget\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "virtual \fB~QDaqPlotWidget\fP ()"
.br
.ti -1c
.RI "QString \fBtitle\fP () const"
.br
.ti -1c
.RI "QString \fBxlabel\fP () const"
.br
.ti -1c
.RI "QString \fBylabel\fP () const"
.br
.ti -1c
.RI "bool \fBautoScaleX\fP () const"
.br
.ti -1c
.RI "bool \fBautoScaleY\fP () const"
.br
.ti -1c
.RI "bool \fBtimeScaleX\fP () const"
.br
.ti -1c
.RI "bool \fBtimeScaleY\fP () const"
.br
.ti -1c
.RI "bool \fBlogScaleX\fP () const"
.br
.ti -1c
.RI "bool \fBlogScaleY\fP () const"
.br
.ti -1c
.RI "bool \fBgrid\fP () const"
.br
.ti -1c
.RI "QPointF \fBxlim\fP () const"
.br
.ti -1c
.RI "QPointF \fBylim\fP () const"
.br
.ti -1c
.RI "void \fBsetTitle\fP (const QString &s)"
.br
.ti -1c
.RI "void \fBsetXLabel\fP (const QString &s)"
.br
.ti -1c
.RI "void \fBsetYLabel\fP (const QString &s)"
.br
.ti -1c
.RI "void \fBsetAutoScaleX\fP (bool on)"
.br
.ti -1c
.RI "void \fBsetAutoScaleY\fP (bool on)"
.br
.ti -1c
.RI "void \fBsetTimeScaleX\fP (bool on)"
.br
.ti -1c
.RI "void \fBsetTimeScaleY\fP (bool on)"
.br
.ti -1c
.RI "void \fBsetLogScaleX\fP (bool on)"
.br
.ti -1c
.RI "void \fBsetLogScaleY\fP (bool on)"
.br
.ti -1c
.RI "void \fBsetGrid\fP (bool on)"
.br
.ti -1c
.RI "void \fBsetXlim\fP (const QPointF &v)"
.br
.ti -1c
.RI "void \fBsetYlim\fP (const QPointF &v)"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const"
.br
.ti -1c
.RI "virtual QSize \fBminimumSizeHint\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBtitle\fP"
.br
.ti -1c
.RI "QString \fBxlabel\fP"
.br
.ti -1c
.RI "QString \fBylabel\fP"
.br
.ti -1c
.RI "bool \fBautoScaleX\fP"
.br
.ti -1c
.RI "bool \fBautoScaleY\fP"
.br
.ti -1c
.RI "bool \fBtimeScaleX\fP"
.br
.ti -1c
.RI "bool \fBtimeScaleY\fP"
.br
.ti -1c
.RI "bool \fBlogScaleX\fP"
.br
.ti -1c
.RI "bool \fBlogScaleY\fP"
.br
.ti -1c
.RI "bool \fBgrid\fP"
.br
.ti -1c
.RI "QPointF \fBxlim\fP"
.br
.ti -1c
.RI "QPointF \fBylim\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file QDaqPlotWidget\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqPlotWidget::QDaqPlotWidget (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 201 of file QDaqPlotWidget\&.cpp\&.
.SS "QDaqPlotWidget::~QDaqPlotWidget ()\fC [virtual]\fP"

.PP
Definition at line 269 of file QDaqPlotWidget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool QDaqPlotWidget::autoScaleX () const"

.PP
Definition at line 286 of file QDaqPlotWidget\&.cpp\&.
.SS "bool QDaqPlotWidget::autoScaleY () const"

.PP
Definition at line 290 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::clear ()\fC [slot]\fP"

.PP
Definition at line 591 of file QDaqPlotWidget\&.cpp\&.
.SS "bool QDaqPlotWidget::grid () const\fC [inline]\fP"

.PP
Definition at line 60 of file QDaqPlotWidget\&.h\&.
.SS "bool QDaqPlotWidget::logScaleX () const\fC [inline]\fP"

.PP
Definition at line 58 of file QDaqPlotWidget\&.h\&.
.SS "bool QDaqPlotWidget::logScaleY () const\fC [inline]\fP"

.PP
Definition at line 59 of file QDaqPlotWidget\&.h\&.
.SS "QSize QDaqPlotWidget::minimumSizeHint () const\fC [virtual]\fP"

.PP
Definition at line 600 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::plot (const \fBQDaqVector\fP & x, const \fBQDaqVector\fP & y, const QColor & clr = \fCQColor()\fP)\fC [slot]\fP"

.PP
Definition at line 537 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::plot (const \fBQDaqVector\fP & x, const \fBQDaqVector\fP & y, const QString & attr, const QColor & clr = \fCQColor()\fP)\fC [slot]\fP"

.PP
Definition at line 378 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::setAutoScaleX (bool on)"

.PP
Definition at line 320 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::setAutoScaleY (bool on)"

.PP
Definition at line 324 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::setGrid (bool on)"

.PP
Definition at line 356 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::setLogScaleX (bool on)"

.PP
Definition at line 342 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::setLogScaleY (bool on)"

.PP
Definition at line 349 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::setTimeScaleX (bool on)"

.PP
Definition at line 328 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::setTimeScaleY (bool on)"

.PP
Definition at line 335 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::setTitle (const QString & s)"

.PP
Definition at line 308 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::setXLabel (const QString & s)"

.PP
Definition at line 312 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::setXlim (const QPointF & v)"

.PP
Definition at line 363 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::setYLabel (const QString & s)"

.PP
Definition at line 316 of file QDaqPlotWidget\&.cpp\&.
.SS "void QDaqPlotWidget::setYlim (const QPointF & v)"

.PP
Definition at line 367 of file QDaqPlotWidget\&.cpp\&.
.SS "QSize QDaqPlotWidget::sizeHint () const\fC [virtual]\fP"

.PP
Definition at line 604 of file QDaqPlotWidget\&.cpp\&.
.SS "bool QDaqPlotWidget::timeScaleX () const\fC [inline]\fP"

.PP
Definition at line 56 of file QDaqPlotWidget\&.h\&.
.SS "bool QDaqPlotWidget::timeScaleY () const\fC [inline]\fP"

.PP
Definition at line 57 of file QDaqPlotWidget\&.h\&.
.SS "QString QDaqPlotWidget::title () const"

.PP
Definition at line 274 of file QDaqPlotWidget\&.cpp\&.
.SS "QString QDaqPlotWidget::xlabel () const"

.PP
Definition at line 278 of file QDaqPlotWidget\&.cpp\&.
.SS "QPointF QDaqPlotWidget::xlim () const"

.PP
Definition at line 294 of file QDaqPlotWidget\&.cpp\&.
.SS "QString QDaqPlotWidget::ylabel () const"

.PP
Definition at line 282 of file QDaqPlotWidget\&.cpp\&.
.SS "QPointF QDaqPlotWidget::ylim () const"

.PP
Definition at line 299 of file QDaqPlotWidget\&.cpp\&.
.SH "Property Documentation"
.PP 
.SS "bool QDaqPlotWidget::autoScaleX\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file QDaqPlotWidget\&.h\&.
.SS "bool QDaqPlotWidget::autoScaleY\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file QDaqPlotWidget\&.h\&.
.SS "bool QDaqPlotWidget::grid\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file QDaqPlotWidget\&.h\&.
.SS "bool QDaqPlotWidget::logScaleX\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file QDaqPlotWidget\&.h\&.
.SS "bool QDaqPlotWidget::logScaleY\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file QDaqPlotWidget\&.h\&.
.SS "bool QDaqPlotWidget::timeScaleX\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file QDaqPlotWidget\&.h\&.
.SS "bool QDaqPlotWidget::timeScaleY\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file QDaqPlotWidget\&.h\&.
.SS "QString QDaqPlotWidget::title\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file QDaqPlotWidget\&.h\&.
.SS "QString QDaqPlotWidget::xlabel\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file QDaqPlotWidget\&.h\&.
.SS "QPointF QDaqPlotWidget::xlim\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file QDaqPlotWidget\&.h\&.
.SS "QString QDaqPlotWidget::ylabel\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file QDaqPlotWidget\&.h\&.
.SS "QPointF QDaqPlotWidget::ylim\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file QDaqPlotWidget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
