.TH "QDaqConsoleTabWidget" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqConsoleTabWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqConsole\&.h>\fP
.PP
Inherits QTabWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBaddConsole\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqConsoleTabWidget\fP (QWidget *parent=0)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBtabRemoved\fP (int index)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file QDaqConsole\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqConsoleTabWidget::QDaqConsoleTabWidget (QWidget * parent = \fC0\fP)"

.PP
Definition at line 196 of file QDaqConsole\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void QDaqConsoleTabWidget::addConsole ()\fC [slot]\fP"

.PP
Definition at line 203 of file QDaqConsole\&.cpp\&.
.SS "void QDaqConsoleTabWidget::tabRemoved (int index)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 213 of file QDaqConsole\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
