.TH "QDaqFilter" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqFilter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqFilter\&.h>\fP
.PP
Inherits \fBQDaqJob\fP\&.
.PP
Inherited by \fBQDaqFOPDT\fP, \fBQDaqInterpolator\fP, \fBQDaqLinearCorrelator\fP, and \fBQDaqPid\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqFilter\fP (const QString &name)"
.br
.ti -1c
.RI "virtual int \fBnInputChannels\fP () const =0"
.br
.ti -1c
.RI "virtual int \fBnOutputChannels\fP () const =0"
.br
.ti -1c
.RI "\fBQDaqObjectList\fP \fBinputChannels\fP () const"
.br
.ti -1c
.RI "\fBQDaqObjectList\fP \fBoutputChannels\fP () const"
.br
.ti -1c
.RI "void \fBsetInputChannels\fP (\fBQDaqObjectList\fP lst)"
.br
.ti -1c
.RI "void \fBsetOutputChannels\fP (\fBQDaqObjectList\fP lst)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBarm_\fP ()"
.br
.ti -1c
.RI "virtual bool \fBrun\fP ()"
.br
.RI "This function performs the actual task of this \fBQDaqJob\fP\&. "
.ti -1c
.RI "virtual bool \fBfilterinit\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBfilterfunc\fP (const double *in, double *out)=0"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBnInputChannels\fP"
.br
.RI "Number of input channels for this filter\&. "
.ti -1c
.RI "int \fBnOutputChannels\fP"
.br
.RI "Number of output channels for this filter\&. "
.ti -1c
.RI "\fBQDaqObjectList\fP \fBinputChannels\fP"
.br
.RI "A QList of the input channels for this filter\&. "
.ti -1c
.RI "\fBQDaqObjectList\fP \fBoutputChannels\fP"
.br
.RI "A QList of the output channels for this filter\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file QDaqFilter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqFilter::QDaqFilter (const QString & name)\fC [explicit]\fP"

.PP
Definition at line 4 of file QDaqFilter\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool QDaqFilter::arm_ ()\fC [protected]\fP, \fC [virtual]\fP"
Performs internal initialization for the job\&.
.PP
It is called by the \fBsetArmed()\fP function\&.
.PP
This function can be reimplemented to perform specific initialization for a job\&. The parent class \fBarm_()\fP function should be called afterwards\&.
.PP
In the default implementation, if a \fBloopEngine()\fP exists the script code is checked against the script engine for errors\&.
.PP
If initialization is sucessfull it returns true, otherwise the function returns false\&. 
.PP
Reimplemented from \fBQDaqJob\fP\&.
.PP
Definition at line 106 of file QDaqFilter\&.cpp\&.
.SS "virtual bool QDaqFilter::filterfunc (const double * in, double * out)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBQDaqPid\fP, \fBQDaqInterpolator\fP, \fBQDaqFOPDT\fP, and \fBQDaqLinearCorrelator\fP\&.
.SS "virtual bool QDaqFilter::filterinit ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBQDaqPid\fP, \fBQDaqInterpolator\fP, \fBQDaqFOPDT\fP, and \fBQDaqLinearCorrelator\fP\&.
.SS "\fBQDaqObjectList\fP QDaqFilter::inputChannels () const"

.PP
Definition at line 10 of file QDaqFilter\&.cpp\&.
.SS "virtual int QDaqFilter::nInputChannels () const\fC [pure virtual]\fP"

.PP
Implemented in \fBQDaqPid\fP, \fBQDaqInterpolator\fP, \fBQDaqFOPDT\fP, and \fBQDaqLinearCorrelator\fP\&.
.SS "virtual int QDaqFilter::nOutputChannels () const\fC [pure virtual]\fP"

.PP
Implemented in \fBQDaqPid\fP, \fBQDaqInterpolator\fP, \fBQDaqFOPDT\fP, and \fBQDaqLinearCorrelator\fP\&.
.SS "\fBQDaqObjectList\fP QDaqFilter::outputChannels () const"

.PP
Definition at line 17 of file QDaqFilter\&.cpp\&.
.SS "bool QDaqFilter::run ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
This function performs the actual task of this \fBQDaqJob\fP\&. It can be reimplemented in subclasses to define the specific job that must be performed\&.
.PP
In the base implementation, it executes the script code if available\&.
.PP
\fBReturns\fP
.RS 4
false if a serious error occured, true otherwise\&. 
.RE
.PP

.PP
Reimplemented from \fBQDaqJob\fP\&.
.PP
Definition at line 76 of file QDaqFilter\&.cpp\&.
.SS "void QDaqFilter::setInputChannels (\fBQDaqObjectList\fP lst)"

.PP
Definition at line 26 of file QDaqFilter\&.cpp\&.
.SS "void QDaqFilter::setOutputChannels (\fBQDaqObjectList\fP lst)"

.PP
Definition at line 51 of file QDaqFilter\&.cpp\&.
.SH "Property Documentation"
.PP 
.SS "\fBQDaqObjectList\fP QDaqFilter::inputChannels\fC [read]\fP, \fC [write]\fP"

.PP
A QList of the input channels for this filter\&. 
.PP
Definition at line 1 of file QDaqFilter\&.h\&.
.SS "int QDaqFilter::nInputChannels\fC [read]\fP"

.PP
Number of input channels for this filter\&. 
.PP
Definition at line 1 of file QDaqFilter\&.h\&.
.SS "int QDaqFilter::nOutputChannels\fC [read]\fP"

.PP
Number of output channels for this filter\&. 
.PP
Definition at line 1 of file QDaqFilter\&.h\&.
.SS "\fBQDaqObjectList\fP QDaqFilter::outputChannels\fC [read]\fP, \fC [write]\fP"

.PP
A QList of the output channels for this filter\&. 
.PP
Definition at line 1 of file QDaqFilter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
