.TH "D:/tixt/corona/qdaq/plugins/interfaces/qdaqmodbus.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/plugins/interfaces/qdaqmodbus.h
.SH SYNOPSIS
.br
.PP
\fC#include 'qdaqserial\&.h'\fP
.br
\fC#include 'qdaqtcpip\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQDaqModbusRtu\fP"
.br
.RI "A class for accesing a MODBUS/RTU connection\&. "
.ti -1c
.RI "class \fBQDaqModbusTcp\fP"
.br
.RI "A class for accesing a MODBUS/TCP connection\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
