.TH "QDaqWidgetsPlugin" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqWidgetsPlugin
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qdaqwidgetsplugin\&.h>\fP
.PP
Inherits QObject, and QDesignerCustomWidgetCollectionInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqWidgetsPlugin\fP (QObject *parent=0)"
.br
.ti -1c
.RI "virtual QList< QDesignerCustomWidgetInterface * > \fBcustomWidgets\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file qdaqwidgetsplugin\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqWidgetsPlugin::QDaqWidgetsPlugin (QObject * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 6 of file qdaqwidgetsplugin\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QList< QDesignerCustomWidgetInterface * > QDaqWidgetsPlugin::customWidgets () const\fC [virtual]\fP"

.PP
Definition at line 15 of file qdaqwidgetsplugin\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
