.TH "D:/tixt/corona/qdaq/lib/gui/QDaqScriptEditor.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/gui/QDaqScriptEditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QtGui>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include 'QDaqScriptEditor\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
