.TH "D:/tixt/corona/qdaq/lib/core/QDaqRoot.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/QDaqRoot.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqRoot\&.h'\fP
.br
\fC#include 'QDaqJob\&.h'\fP
.br
\fC#include 'QDaqLogFile\&.h'\fP
.br
\fC#include 'QDaqChannel\&.h'\fP
.br
\fC#include 'QDaqDataBuffer\&.h'\fP
.br
\fC#include 'QDaqSession\&.h'\fP
.br
\fC#include 'QDaqIde\&.h'\fP
.br
\fC#include 'QDaqInterface\&.h'\fP
.br
\fC#include 'QDaqDevice\&.h'\fP
.br
\fC#include 'QDaqFilter\&.h'\fP
.br
\fC#include 'qdaqplugin\&.h'\fP
.br
\fC#include <QCoreApplication>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QPluginLoader>\fP
.br
\fC#include <QLibraryInfo>\fP
.br
\fC#include <QDebug>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBjobDisarmHelper\fP (\fBQDaqObjectList\fP lst)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void jobDisarmHelper (\fBQDaqObjectList\fP lst)"

.PP
Definition at line 60 of file QDaqRoot\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
