.TH "QDaqObjectBrowser" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqObjectBrowser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqObjectBrowser\&.h>\fP
.PP
Inherits QSplitter\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBcurrentObjectChanged\fP (\fBQDaqObject\fP *obj)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqObjectBrowser\fP (QWidget *p=0)"
.br
.ti -1c
.RI "virtual \fB~QDaqObjectBrowser\fP (void)"
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBonItemActivated\fP (const QModelIndex &index)"
.br
.ti -1c
.RI "void \fBonSetByUser\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBQDaqObjectModel\fP * \fBmodel\fP"
.br
.ti -1c
.RI "QTreeView * \fBtreeView\fP"
.br
.ti -1c
.RI "QTabWidget * \fBtabWidget\fP"
.br
.ti -1c
.RI "\fBQDaqPropertyBrowser\fP * \fBpropertyBrowser\fP"
.br
.ti -1c
.RI "\fBQDaqFunctionBrowser\fP * \fBfunctionBrowser\fP"
.br
.ti -1c
.RI "QLineEdit * \fBcurrentObject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file QDaqObjectBrowser\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqObjectBrowser::QDaqObjectBrowser (QWidget * p = \fC0\fP)"

.PP
Definition at line 20 of file QDaqObjectBrowser\&.cpp\&.
.SS "QDaqObjectBrowser::~QDaqObjectBrowser (void)\fC [virtual]\fP"

.PP
Definition at line 55 of file QDaqObjectBrowser\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void QDaqObjectBrowser::currentObjectChanged (\fBQDaqObject\fP * obj)\fC [signal]\fP"

.SS "void QDaqObjectBrowser::onItemActivated (const QModelIndex & index)\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 59 of file QDaqObjectBrowser\&.cpp\&.
.SS "void QDaqObjectBrowser::onSetByUser ()\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 67 of file QDaqObjectBrowser\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QLineEdit* QDaqObjectBrowser::currentObject\fC [protected]\fP"

.PP
Definition at line 44 of file QDaqObjectBrowser\&.h\&.
.SS "\fBQDaqFunctionBrowser\fP* QDaqObjectBrowser::functionBrowser\fC [protected]\fP"

.PP
Definition at line 43 of file QDaqObjectBrowser\&.h\&.
.SS "\fBQDaqObjectModel\fP* QDaqObjectBrowser::model\fC [protected]\fP"

.PP
Definition at line 39 of file QDaqObjectBrowser\&.h\&.
.SS "\fBQDaqPropertyBrowser\fP* QDaqObjectBrowser::propertyBrowser\fC [protected]\fP"

.PP
Definition at line 42 of file QDaqObjectBrowser\&.h\&.
.SS "QTabWidget* QDaqObjectBrowser::tabWidget\fC [protected]\fP"

.PP
Definition at line 41 of file QDaqObjectBrowser\&.h\&.
.SS "QTreeView* QDaqObjectBrowser::treeView\fC [protected]\fP"

.PP
Definition at line 40 of file QDaqObjectBrowser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
