.TH "D:/tixt/corona/qdaq/lib/daq/QDaqDevice.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/daq/QDaqDevice.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqDevice\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
