.TH "D:/tixt/corona/qdaq/lib/gui/QDaqObjectController.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/gui/QDaqObjectController.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QMetaObject>\fP
.br
\fC#include <QMetaProperty>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QScrollArea>\fP
.br
\fC#include 'QDaqObjectController\&.h'\fP
.br
\fC#include 'variantmanager\&.h'\fP
.br
\fC#include 'qtgroupboxpropertybrowser\&.h'\fP
.br
\fC#include 'qttreepropertybrowser\&.h'\fP
.br
\fC#include 'qtpropertybrowser\&.h'\fP
.br
\fC#include 'QDaqVector\&.h'\fP
.br
\fC#include 'QDaqObject\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQDaqObjectControllerPrivate\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBisQDaqType\fP (int type)"
.br
.ti -1c
.RI "bool \fBisQDaqType\fP (const QVariant &v)"
.br
.ti -1c
.RI "template<class T > QString \fBqdaqVectorTypeToString\fP (const QVariant &var)"
.br
.ti -1c
.RI "QString \fBqdaqTypeToString\fP (const QVariant &v)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool isQDaqType (const QVariant & v)"

.PP
Definition at line 72 of file QDaqObjectController\&.cpp\&.
.SS "bool isQDaqType (int type)"

.PP
Definition at line 62 of file QDaqObjectController\&.cpp\&.
.SS "QString qdaqTypeToString (const QVariant & v)"

.PP
Definition at line 103 of file QDaqObjectController\&.cpp\&.
.SS "template<class T > QString qdaqVectorTypeToString (const QVariant & var)"

.PP
Definition at line 91 of file QDaqObjectController\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
