.TH "QDaqJob::JobList" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqJob::JobList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqJob\&.h>\fP
.PP
Inherits QList< QDaqJob * >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBexec\fP ()"
.br
.ti -1c
.RI "void \fBlock\fP ()"
.br
.ti -1c
.RI "void \fBunlock\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 169 of file QDaqJob\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool QDaqJob::JobList::exec ()\fC [inline]\fP"

.PP
Definition at line 172 of file QDaqJob\&.h\&.
.SS "void QDaqJob::JobList::lock ()\fC [inline]\fP"

.PP
Definition at line 177 of file QDaqJob\&.h\&.
.SS "void QDaqJob::JobList::unlock ()\fC [inline]\fP"

.PP
Definition at line 178 of file QDaqJob\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
