.TH "D:/tixt/corona/qdaq/lib/core/QDaqObject.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/QDaqObject.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QList>\fP
.br
\fC#include <QSet>\fP
.br
\fC#include <QMetaType>\fP
.br
\fC#include <QScriptable>\fP
.br
\fC#include <QMutex>\fP
.br
\fC#include 'QDaqGlobal\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBQDaqError\fP"
.br
.ti -1c
.RI "class \fBQDaqObject\fP"
.br
.ti -1c
.RI "class \fBQDaqErrorQueue\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBH5\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBERROR_QUEUE_DEPTH\fP   1000"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QList< \fBQDaqObject\fP * > \fBQDaqObjectList\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ERROR_QUEUE_DEPTH   1000"

.PP
Definition at line 295 of file QDaqObject\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
