.TH "D:/tixt/corona/qdaq/lib/core/QDaqChannel.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/QDaqChannel.h
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqJob\&.h'\fP
.br
\fC#include 'QDaqTypes\&.h'\fP
.br
\fC#include 'math_util\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQDaqChannel\fP"
.br
.RI "A class that represent a stream of numerical data, a signal\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmu\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
