.TH "D:/tixt/corona/qdaq/lib/core/QDaqGlobal.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/QDaqGlobal.h
.SH SYNOPSIS
.br
.PP
\fC#include <qglobal\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBQDaq\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQDAQ_EXPORT\fP   Q_DECL_IMPORT"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBQDAQ_EXPORT\fP const char * \fBQDaq::Version\fP ()"
.br
.ti -1c
.RI "\fBQDAQ_EXPORT\fP const char * \fBQDaq::QtVersion\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QDAQ_EXPORT   Q_DECL_IMPORT"

.PP
Definition at line 19 of file QDaqGlobal\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
