.TH "QDaq" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaq
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBQDAQ_EXPORT\fP const char * \fBVersion\fP ()"
.br
.ti -1c
.RI "\fBQDAQ_EXPORT\fP const char * \fBQtVersion\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char * QDaq::QtVersion ()"

.PP
Definition at line 22 of file QDaqObject\&.cpp\&.
.SS "const char * QDaq::Version ()"

.PP
Definition at line 20 of file QDaqObject\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
