.TH "D:/tixt/corona/qdaq/lib/core/qdaqplugin.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/qdaqplugin.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtPlugin>\fP
.br
\fC#include <QMetaObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQDaqPlugin\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQDaqPluginIID\fP   'org\&.qdaq\&.plugin'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QDaqPluginIID   'org\&.qdaq\&.plugin'"

.PP
Definition at line 17 of file qdaqplugin\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
