.TH "QDaqLogFile" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDaqLogFile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqLogFile\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQDaqLogFile\fP (bool tm=true, QChar delim=QChar('\\t'), QObject *parent=0)"
.br
.ti -1c
.RI "\fB~QDaqLogFile\fP ()"
.br
.ti -1c
.RI "bool \fBopen\fP (const QString &fname)"
.br
.ti -1c
.RI "bool \fBisOpen\fP ()"
.br
.ti -1c
.RI "\fBQDaqLogFile\fP & \fBoperator<<\fP (const QString &str)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QString \fBgetDecoratedName\fP (const QString &simpleName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file QDaqLogFile\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QDaqLogFile::QDaqLogFile (bool tm = \fCtrue\fP, QChar delim = \fCQChar('\\t')\fP, QObject * parent = \fC0\fP)"

.PP
Definition at line 11 of file QDaqLogFile\&.cpp\&.
.SS "QDaqLogFile::~QDaqLogFile ()"

.PP
Definition at line 17 of file QDaqLogFile\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString QDaqLogFile::getDecoratedName (const QString & simpleName)\fC [static]\fP"

.PP
Definition at line 37 of file QDaqLogFile\&.cpp\&.
.SS "bool QDaqLogFile::isOpen ()"

.PP
Definition at line 31 of file QDaqLogFile\&.cpp\&.
.SS "bool QDaqLogFile::open (const QString & fname)"

.PP
Definition at line 22 of file QDaqLogFile\&.cpp\&.
.SS "\fBQDaqLogFile\fP & QDaqLogFile::operator<< (const QString & str)"

.PP
Definition at line 45 of file QDaqLogFile\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
