.TH "D:/tixt/corona/qdaq/lib/gui/QDaqWindow.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/gui/QDaqWindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqWindow\&.h'\fP
.br
\fC#include 'QDaqIde\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QCloseEvent>\fP
.br
\fC#include <QHBoxLayout>\fP
.br
\fC#include <QKeyEvent>\fP
.br
\fC#include <QAction>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include 'QDaqRoot\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
