.TH "D:/tixt/corona/qdaq/plugins/filters/qdaqlinearcorrelator.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/plugins/filters/qdaqlinearcorrelator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qdaqlinearcorrelator\&.h'\fP
.br
\fC#include 'linefit\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
