.TH "QLedPlugin" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QLedPlugin
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qledplugin\&.h>\fP
.PP
Inherits QObject, and QDesignerCustomWidgetInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQLedPlugin\fP (QObject *parent=0)"
.br
.ti -1c
.RI "bool \fBisContainer\fP () const"
.br
.ti -1c
.RI "bool \fBisInitialized\fP () const"
.br
.ti -1c
.RI "QIcon \fBicon\fP () const"
.br
.ti -1c
.RI "QString \fBdomXml\fP () const"
.br
.ti -1c
.RI "QString \fBgroup\fP () const"
.br
.ti -1c
.RI "QString \fBincludeFile\fP () const"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "QString \fBtoolTip\fP () const"
.br
.ti -1c
.RI "QString \fBwhatsThis\fP () const"
.br
.ti -1c
.RI "QWidget * \fBcreateWidget\fP (QWidget *parent)"
.br
.ti -1c
.RI "void \fBinitialize\fP (QDesignerFormEditorInterface *core)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file qledplugin\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QLedPlugin::QLedPlugin (QObject * parent = \fC0\fP)"

.PP
Definition at line 6 of file qledplugin\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QWidget * QLedPlugin::createWidget (QWidget * parent)"

.PP
Definition at line 27 of file qledplugin\&.cpp\&.
.SS "QString QLedPlugin::domXml () const"

.PP
Definition at line 62 of file qledplugin\&.cpp\&.
.SS "QString QLedPlugin::group () const"

.PP
Definition at line 37 of file qledplugin\&.cpp\&.
.SS "QIcon QLedPlugin::icon () const"

.PP
Definition at line 42 of file qledplugin\&.cpp\&.
.SS "QString QLedPlugin::includeFile () const"

.PP
Definition at line 67 of file qledplugin\&.cpp\&.
.SS "void QLedPlugin::initialize (QDesignerFormEditorInterface * core)"

.PP
Definition at line 12 of file qledplugin\&.cpp\&.
.SS "bool QLedPlugin::isContainer () const"

.PP
Definition at line 57 of file qledplugin\&.cpp\&.
.SS "bool QLedPlugin::isInitialized () const"

.PP
Definition at line 22 of file qledplugin\&.cpp\&.
.SS "QString QLedPlugin::name () const"

.PP
Definition at line 32 of file qledplugin\&.cpp\&.
.SS "QString QLedPlugin::toolTip () const"

.PP
Definition at line 47 of file qledplugin\&.cpp\&.
.SS "QString QLedPlugin::whatsThis () const"

.PP
Definition at line 52 of file qledplugin\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
