.TH "QTimerThread" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QTimerThread \- A timer thread class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qtimerthread\&.h>\fP
.PP
Inherits QThread\&.
.PP
Inherited by \fBQDaqLoop::LoopTimerThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQTimerThread\fP ()"
.br
.ti -1c
.RI "virtual \fB~QTimerThread\fP ()"
.br
.ti -1c
.RI "int \fBinterval\fP () const"
.br
.ti -1c
.RI "void \fBsetInterval\fP (int ms)"
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "virtual void \fBtimer_func\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBinterval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A timer thread class\&. 

\fBQTimerThread\fP inheritis QThread and uses internally QTimer to implement its functionality\&.
.PP
After calling start() a thread is spawned and the function \fBtimer_func()\fP is called periodically with period equal to the interval property (in ms)\&.
.PP
To use the class one has to subclass \fBQTimerThread\fP reimplement \fBtimer_func()\fP\&. Note that \fBtimer_func()\fP is executed from the sepatrate timer thread thus and the user is responsible for synchronization issues\&.
.PP
The accuracy of the timer depends on Qt's QTimer class\&. According to their docs QTimer uses the best OS timing routines in each case\&. 
.PP
Definition at line 27 of file qtimerthread\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QTimerThread::QTimerThread ()"

.PP
Definition at line 3 of file qtimerthread\&.cpp\&.
.SS "QTimerThread::~QTimerThread ()\fC [virtual]\fP"

.PP
Definition at line 11 of file qtimerthread\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int QTimerThread::interval () const\fC [inline]\fP"

.PP
Definition at line 47 of file qtimerthread\&.h\&.
.SS "void QTimerThread::run ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 17 of file qtimerthread\&.cpp\&.
.SS "void QTimerThread::setInterval (int ms)\fC [inline]\fP"

.PP
Definition at line 48 of file qtimerthread\&.h\&.
.SS "virtual void QTimerThread::timer_func ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP, \fC [slot]\fP"

.PP
Reimplemented in \fBQDaqLoop::LoopTimerThread\fP\&.
.PP
Definition at line 37 of file qtimerthread\&.h\&.
.SH "Property Documentation"
.PP 
.SS "int QTimerThread::interval\fC [read]\fP, \fC [write]\fP"
Timer repetition interval in ms\&. 
.PP
Definition at line 1 of file qtimerthread\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
