.TH "D:/tixt/corona/qdaq/plugins/filters/relaytuner.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/plugins/filters/relaytuner.h
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBautotuner< T >\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   3\&.1415926535897932384626433832795"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PI   3\&.1415926535897932384626433832795"

.PP
Definition at line 7 of file relaytuner\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
