.TH "SidebarWidget" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SidebarWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSidebarWidget\fP (\fBJSEdit\fP *editor)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QVector< \fBBlockInfo\fP > \fBlineNumbers\fP"
.br
.ti -1c
.RI "QColor \fBbackgroundColor\fP"
.br
.ti -1c
.RI "QColor \fBlineNumberColor\fP"
.br
.ti -1c
.RI "QColor \fBindicatorColor\fP"
.br
.ti -1c
.RI "QColor \fBfoldIndicatorColor\fP"
.br
.ti -1c
.RI "QFont \fBfont\fP"
.br
.ti -1c
.RI "int \fBfoldIndicatorWidth\fP"
.br
.ti -1c
.RI "QPixmap \fBrightArrowIcon\fP"
.br
.ti -1c
.RI "QPixmap \fBdownArrowIcon\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBmousePressEvent\fP (QMouseEvent *event)"
.br
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 478 of file jsedit\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SidebarWidget::SidebarWidget (\fBJSEdit\fP * editor)"

.PP
Definition at line 496 of file jsedit\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void SidebarWidget::mousePressEvent (QMouseEvent * event)\fC [protected]\fP"

.PP
Definition at line 506 of file jsedit\&.cpp\&.
.SS "void SidebarWidget::paintEvent (QPaintEvent * event)\fC [protected]\fP"

.PP
Definition at line 529 of file jsedit\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QColor SidebarWidget::backgroundColor"

.PP
Definition at line 483 of file jsedit\&.cpp\&.
.SS "QPixmap SidebarWidget::downArrowIcon"

.PP
Definition at line 490 of file jsedit\&.cpp\&.
.SS "QColor SidebarWidget::foldIndicatorColor"

.PP
Definition at line 486 of file jsedit\&.cpp\&.
.SS "int SidebarWidget::foldIndicatorWidth"

.PP
Definition at line 488 of file jsedit\&.cpp\&.
.SS "QFont SidebarWidget::font"

.PP
Definition at line 487 of file jsedit\&.cpp\&.
.SS "QColor SidebarWidget::indicatorColor"

.PP
Definition at line 485 of file jsedit\&.cpp\&.
.SS "QColor SidebarWidget::lineNumberColor"

.PP
Definition at line 484 of file jsedit\&.cpp\&.
.SS "QVector<\fBBlockInfo\fP> SidebarWidget::lineNumbers"

.PP
Definition at line 482 of file jsedit\&.cpp\&.
.SS "QPixmap SidebarWidget::rightArrowIcon"

.PP
Definition at line 489 of file jsedit\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
