.TH "TimeScaleEngine" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeScaleEngine
.SH SYNOPSIS
.br
.PP
.PP
Inherits QwtLinearScaleEngine\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBautoScale\fP (int maxSteps, double &x1, double &x2, double &stepSize) const"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static double \fBconversion_factor\fP (double T)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 127 of file QDaqPlotWidget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void TimeScaleEngine::autoScale (int maxSteps, double & x1, double & x2, double & stepSize) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 140 of file QDaqPlotWidget\&.cpp\&.
.SS "static double TimeScaleEngine::conversion_factor (double T)\fC [inline]\fP, \fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 130 of file QDaqPlotWidget\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
