.TH "TimeScaleDraw" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeScaleDraw
.SH SYNOPSIS
.br
.PP
.PP
Inherits QwtScaleDraw\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimeScaleDraw\fP ()"
.br
.ti -1c
.RI "virtual QwtText \fBlabel\fP (double v) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 102 of file QDaqPlotWidget\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TimeScaleDraw::TimeScaleDraw ()\fC [inline]\fP"

.PP
Definition at line 105 of file QDaqPlotWidget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual QwtText TimeScaleDraw::label (double v) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 108 of file QDaqPlotWidget\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
