.TH "VectorClass" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VectorClass
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vectorclass\&.h>\fP
.PP
Inherits QObject, and QScriptClass\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVectorClass\fP (QScriptEngine *engine)"
.br
.RI "[0] "
.ti -1c
.RI "\fB~VectorClass\fP ()"
.br
.RI "[0] "
.ti -1c
.RI "QScriptValue \fBconstructor\fP ()"
.br
.ti -1c
.RI "QScriptValue \fBnewInstance\fP (int size=0)"
.br
.RI "[10] "
.ti -1c
.RI "QScriptValue \fBnewInstance\fP (const \fBQDaqVector\fP &ba)"
.br
.RI "[10] "
.ti -1c
.RI "QueryFlags \fBqueryProperty\fP (const QScriptValue &object, const QScriptString &\fBname\fP, QueryFlags flags, uint *id)"
.br
.RI "[3] "
.ti -1c
.RI "QScriptValue \fBproperty\fP (const QScriptValue &object, const QScriptString &\fBname\fP, uint id)"
.br
.RI "[3] "
.ti -1c
.RI "void \fBsetProperty\fP (QScriptValue &object, const QScriptString &\fBname\fP, uint id, const QScriptValue &value)"
.br
.RI "[4] "
.ti -1c
.RI "QScriptValue::PropertyFlags \fBpropertyFlags\fP (const QScriptValue &object, const QScriptString &\fBname\fP, uint id)"
.br
.RI "[5] "
.ti -1c
.RI "QScriptClassPropertyIterator * \fBnewIterator\fP (const QScriptValue &object)"
.br
.RI "[6] "
.ti -1c
.RI "QString \fBname\fP () const"
.br
.RI "[7] "
.ti -1c
.RI "QScriptValue \fBprototype\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file vectorclass\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VectorClass::VectorClass (QScriptEngine * engine)"

.PP
[0] 
.PP
Definition at line 38 of file vectorclass\&.cpp\&.
.SS "VectorClass::~VectorClass ()"

.PP
[0] 
.PP
Definition at line 60 of file vectorclass\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QScriptValue VectorClass::constructor ()"

.PP
Definition at line 170 of file vectorclass\&.cpp\&.
.SS "QString VectorClass::name () const"

.PP
[7] 
.PP
Definition at line 160 of file vectorclass\&.cpp\&.
.SS "QScriptValue VectorClass::newInstance (const \fBQDaqVector\fP & ba)"

.PP
[10] [1] 
.PP
Definition at line 184 of file vectorclass\&.cpp\&.
.SS "QScriptValue VectorClass::newInstance (int size = \fC0\fP)"

.PP
[10] 
.PP
Definition at line 176 of file vectorclass\&.cpp\&.
.SS "QScriptClassPropertyIterator * VectorClass::newIterator (const QScriptValue & object)"

.PP
[6] [7] 
.PP
Definition at line 152 of file vectorclass\&.cpp\&.
.SS "QScriptValue VectorClass::property (const QScriptValue & object, const QScriptString & name, uint id)"

.PP
[3] [4] 
.PP
Definition at line 92 of file vectorclass\&.cpp\&.
.SS "QScriptValue::PropertyFlags VectorClass::propertyFlags (const QScriptValue & object, const QScriptString & name, uint id)"

.PP
[5] [6] 
.PP
Definition at line 138 of file vectorclass\&.cpp\&.
.SS "QScriptValue VectorClass::prototype () const"

.PP
Definition at line 165 of file vectorclass\&.cpp\&.
.SS "QScriptClass::QueryFlags VectorClass::queryProperty (const QScriptValue & object, const QScriptString & name, QueryFlags flags, uint * id)"

.PP
[3] 
.PP
Definition at line 65 of file vectorclass\&.cpp\&.
.SS "void VectorClass::setProperty (QScriptValue & object, const QScriptString & name, uint id, const QScriptValue & value)"

.PP
[4] [5] 
.PP
Definition at line 115 of file vectorclass\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
