.TH "D:/tixt/corona/qdaq/lib/core/vectorclass.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/vectorclass.h
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqTypes\&.h'\fP
.br
\fC#include <QtCore/QObject>\fP
.br
\fC#include <QtScript/QScriptClass>\fP
.br
\fC#include <QtScript/QScriptString>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVectorClass\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
