.TH "D:/tixt/corona/qdaq/lib/core/vectorprototype.cpp" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/vectorprototype.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vectorprototype\&.h'\fP
.br
\fC#include <QtScript/QScriptEngine>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
