.TH "D:/tixt/corona/qdaq/lib/core/vectorprototype.h" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/tixt/corona/qdaq/lib/core/vectorprototype.h
.SH SYNOPSIS
.br
.PP
\fC#include 'QDaqVector\&.h'\fP
.br
\fC#include <QtCore/QObject>\fP
.br
\fC#include <QtScript/QScriptable>\fP
.br
\fC#include <QtScript/QScriptValue>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVectorPrototype\fP"
.br
.RI "The prototype for the Vector class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
