.TH "VectorClassPropertyIterator" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VectorClassPropertyIterator
.SH SYNOPSIS
.br
.PP
.PP
Inherits QScriptClassPropertyIterator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVectorClassPropertyIterator\fP (const QScriptValue &object, const QList< QScriptString > &lst)"
.br
.RI "[9] "
.ti -1c
.RI "\fB~VectorClassPropertyIterator\fP ()"
.br
.ti -1c
.RI "bool \fBhasNext\fP () const"
.br
.RI "[8] "
.ti -1c
.RI "void \fBnext\fP ()"
.br
.ti -1c
.RI "bool \fBhasPrevious\fP () const"
.br
.ti -1c
.RI "void \fBprevious\fP ()"
.br
.ti -1c
.RI "void \fBtoFront\fP ()"
.br
.ti -1c
.RI "void \fBtoBack\fP ()"
.br
.ti -1c
.RI "QScriptString \fBname\fP () const"
.br
.ti -1c
.RI "uint \fBid\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file vectorclass\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VectorClassPropertyIterator::VectorClassPropertyIterator (const QScriptValue & object, const QList< QScriptString > & lst)"

.PP
[9] 
.PP
Definition at line 255 of file vectorclass\&.cpp\&.
.SS "VectorClassPropertyIterator::~VectorClassPropertyIterator ()"

.PP
Definition at line 261 of file vectorclass\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool VectorClassPropertyIterator::hasNext () const"

.PP
[8] 
.PP
Definition at line 266 of file vectorclass\&.cpp\&.
.SS "bool VectorClassPropertyIterator::hasPrevious () const"

.PP
Definition at line 278 of file vectorclass\&.cpp\&.
.SS "uint VectorClassPropertyIterator::id () const"

.PP
Definition at line 309 of file vectorclass\&.cpp\&.
.SS "QScriptString VectorClassPropertyIterator::name () const"

.PP
Definition at line 302 of file vectorclass\&.cpp\&.
.SS "void VectorClassPropertyIterator::next ()"

.PP
Definition at line 272 of file vectorclass\&.cpp\&.
.SS "void VectorClassPropertyIterator::previous ()"

.PP
Definition at line 283 of file vectorclass\&.cpp\&.
.SS "void VectorClassPropertyIterator::toBack ()"

.PP
Definition at line 295 of file vectorclass\&.cpp\&.
.SS "void VectorClassPropertyIterator::toFront ()"

.PP
Definition at line 289 of file vectorclass\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
