.TH "WidgetVariant" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetVariant
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QDaqDelegates\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBWidgetType\fP { \fBqNone\fP, \fBqUnsupported\fP, \fBqAbstractButton\fP, \fBqAbstractSlider\fP, \fBqSpinBox\fP, \fBqDoubleSpinBox\fP, \fBqLineEdit\fP, \fBqComboBox\fP, \fBqLabel\fP, \fBqLCDNumber\fP, \fBqwtThermo\fP, \fBqdaqLed\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWidgetVariant\fP (QWidget *w=0)"
.br
.ti -1c
.RI "bool \fBisReadable\fP () const"
.br
.ti -1c
.RI "bool \fBisText\fP () const"
.br
.ti -1c
.RI "bool \fBisValid\fP () const"
.br
.ti -1c
.RI "bool \fBisNull\fP () const"
.br
.ti -1c
.RI "bool \fBcanConvert\fP (QVariant::Type t) const"
.br
.ti -1c
.RI "\fBWidgetType\fP \fBtype\fP () const"
.br
.ti -1c
.RI "QWidget * \fBwidget\fP () const"
.br
.ti -1c
.RI "const char * \fBwidgetSignal\fP () const"
.br
.ti -1c
.RI "QVariant \fBread\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP (const QVariant &v)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QPointer< QWidget > \fBwidget_\fP"
.br
.ti -1c
.RI "\fBWidgetType\fP \fBtype_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file QDaqDelegates\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBWidgetVariant::WidgetType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIqNone \fP\fP
.TP
\fB\fIqUnsupported \fP\fP
.TP
\fB\fIqAbstractButton \fP\fP
.TP
\fB\fIqAbstractSlider \fP\fP
.TP
\fB\fIqSpinBox \fP\fP
.TP
\fB\fIqDoubleSpinBox \fP\fP
.TP
\fB\fIqLineEdit \fP\fP
.TP
\fB\fIqComboBox \fP\fP
.TP
\fB\fIqLabel \fP\fP
.TP
\fB\fIqLCDNumber \fP\fP
.TP
\fB\fIqwtThermo \fP\fP
.TP
\fB\fIqdaqLed \fP\fP
.PP
Definition at line 16 of file QDaqDelegates\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WidgetVariant::WidgetVariant (QWidget * w = \fC0\fP)"

.PP
Definition at line 20 of file QDaqDelegates\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool WidgetVariant::canConvert (QVariant::Type t) const"

.PP
Definition at line 34 of file QDaqDelegates\&.cpp\&.
.SS "bool WidgetVariant::isNull () const\fC [inline]\fP"

.PP
Definition at line 41 of file QDaqDelegates\&.h\&.
.SS "bool WidgetVariant::isReadable () const\fC [inline]\fP"

.PP
Definition at line 38 of file QDaqDelegates\&.h\&.
.SS "bool WidgetVariant::isText () const\fC [inline]\fP"

.PP
Definition at line 39 of file QDaqDelegates\&.h\&.
.SS "bool WidgetVariant::isValid () const\fC [inline]\fP"

.PP
Definition at line 40 of file QDaqDelegates\&.h\&.
.SS "QVariant WidgetVariant::read ()"

.PP
Definition at line 61 of file QDaqDelegates\&.cpp\&.
.SS "\fBWidgetType\fP WidgetVariant::type () const\fC [inline]\fP"

.PP
Definition at line 43 of file QDaqDelegates\&.h\&.
.SS "QWidget* WidgetVariant::widget () const\fC [inline]\fP"

.PP
Definition at line 44 of file QDaqDelegates\&.h\&.
.SS "const char * WidgetVariant::widgetSignal () const"

.PP
Definition at line 157 of file QDaqDelegates\&.cpp\&.
.SS "void WidgetVariant::write (const QVariant & v)"

.PP
Definition at line 108 of file QDaqDelegates\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBWidgetType\fP WidgetVariant::type_\fC [protected]\fP"

.PP
Definition at line 33 of file QDaqDelegates\&.h\&.
.SS "QPointer<QWidget> WidgetVariant::widget_\fC [protected]\fP"

.PP
Definition at line 32 of file QDaqDelegates\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
