.TH "Zoomer" 3 "Wed May 20 2020" "Version 0.2.6" "qdaq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zoomer
.SH SYNOPSIS
.br
.PP
.PP
Inherits QwtPlotZoomer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZoomer\fP (int xAxis, int yAxis, QWidget *canvas)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual bool \fBend\fP (bool ok=true)"
.br
.ti -1c
.RI "virtual void \fBwidgetMouseDoubleClickEvent\fP (QMouseEvent *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file QDaqPlotWidget\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zoomer::Zoomer (int xAxis, int yAxis, QWidget * canvas)\fC [inline]\fP"

.PP
Definition at line 58 of file QDaqPlotWidget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Zoomer::begin ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 64 of file QDaqPlotWidget\&.cpp\&.
.SS "virtual bool Zoomer::end (bool ok = \fCtrue\fP)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 86 of file QDaqPlotWidget\&.cpp\&.
.SS "virtual void Zoomer::widgetMouseDoubleClickEvent (QMouseEvent *)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 90 of file QDaqPlotWidget\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for qdaq from the source code\&.
